const veroListEbay = [
	"3M Company",
	"3Skulls Paintball",
	"AAT - The Association of Acounting Technicians",
	"Abercrombie & Fitch",
	"Action Mining Services Inc.",
	"Adobe",
	"ADT",
	"Agora LLC",
	"Air Force One Air Conditioning",
	"Aircraft Technical Publishers",
	"Alaska Airlines",
	"Aleratec, Inc.",
	"Alex Perez",
	"Alfresco Heating",
	"ALIENTECH SRL",
	"All Saints (Retail) Ltd",
	"ALM Productions",
	"Aloe of America, Inc. & Forever Living Products Int'l.",
	"Amari Bliss",
	"AMC Photographics Limited",
	"Americana International Ltd.",
	"American Eagle Outfitters",
	"American Weigh Scales, Inc.",
	"American Welding Society",
	"Americas Drive-In Corp. / Sonic Corp. & Subsidiaries",
	"Amiclubwear.com",
	"Ammodor, LLC",
	"Amway Corporation (US)",
	"Amybug's Attic",
	"AnalogMan Guitar Effects",
	"Andrew James Worldwide",
	"Andy Thomas",
	"Angela LaFramboise",
	"Annenberg Media",
	"Ansonia Records, Inc.",
	"Anvil Forge Art",
	"Apex Tool Group",
	"AQUALIBRA UK",
	"AR15.com",
	"Arduino, LLC",
	"ARIIX, LLC",
	"Artbeats Software, Inc.",
	"Arturia",
	"Ashleigh Talbot",
	"AsKoruBeads",
	"Atlantic Research and Marketing (A.R.M.S.)",
	"Atvimports",
	"Auntie Anne's, Inc.",
	"Austin City Limits/KLRU",
	"Australian Gold, Inc.",
	"Australian Made Campaign Limited",
	"Authentic Brands Group LLC",
	"Autism Speaks, Inc.",
	"Autodata Limited",
	"Auto Meter Products, Inc. (Autometer)",
	"Autoline Industries",
	"Automotive Technologies, Inc.",
	"AutoWin.Eu LTD",
	"Avedis Zildjian, Co.",
	"B&M Racing",
	"B. C. Broncos",
	"B.H.P., Inc. dba Nialaya Jewelry",
	"Bad Monkey Productions",
	"Bally Pinball Fun",
	"Barnett Research and Computer Imaging",
	"Barstool Sports, Inc.",
	"Baume & Mercier",
	"Beachbody, LLC",
	"Bear Grylls Ventures LLP",
	"Bed Band Store",
	"BELDT Labs",
	"Bell Helicopter Textron Inc.",
	"BEMER Int. AG",
	"Ben Kaufman Sales Co.",
	"Benchmade Knife Company, Inc.",
	"Beyond Cell",
	"Beverly Hills MD",
	"BG Soflex, LLC",
	"Bill Lawrence Products",
	"Bill Owen-Cowboy Artist",
	"Billie W. Taylor II, Ph.D.",
	"BINO Products, LLC",
	"Biomic Sciences, LLC",
	"Biotrade Bulgaria Ltd.",
	"BioTrust Nutrition",
	"BISSELL Homecare, Inc.",
	"Bittrex, Inc.",
	"Blackpoint Engineering, LLC",
	"Blitzburgh Sports",
	"Blockware, LLC dba Great Useful Stuff",
	"Bloomberg L.P.",
	"BlossomSugarArt",
	"Bluetooth",
	"Bombardier Recreational Products, Inc.",
	"Bonnie's Plants",
	"Boppy Company, The",
	"Bose Corporation",
	"Botanissa LLC - See U Baby",
	"Boveda, Inc.",
	"Braniff Airways, Incorporated.",
	"Brenda Franklin",
	"Brian Smith",
	"Bridgestone Brands, LLC",
	"Brisant Secure Ltd",
	"British Phonographic Industry Limited",
	"Bronze Gallery",
	"Brother International",
	"Browning Laboratories, Inc.",
	"Bruce Lee Enterprises",
	"Bua, Inc.",
	"Buck Knives, Inc.",
	"Bug Me Video Inc.",
	"Bumbleride Inc.",
	"Burberry Limited",
	"Burlen Fuel System Limited",
	"Bushnell Performance Optics and Tasco Sales Pty Ltd.",
	"Business Software Alliance (EU)",
	"Bwthynbach",
	"Calutech, Inc.",
	"Canadian Standards Association",
	"Canon, Inc.",
	"Canyon Chenille, Inc.",
	"Canyon Dancer Motorcycle Products",
	"Care Creations, Inc.",
	"Car-Freshner Corporation",
	"Carl McCoy (Fields of the Nephilim)",
	"Carleon",
	"Carlstar Group – ITP and Carlisle Brands",
	"Carmen's Vintage Collections",
	"Carmix-GPS",
	"Carrs Coins and Rocks, Inc.",
	"Cartier",
	"CBS Entertainment and Desilu, too, LLC (Unforgettable Licensing)",
	"CBT Nuggets, Inc",
	"CDF Firefighters / CAL FIRE Local 2881",
	"Celebrate Vitamins",
	"CeraNet, Inc.",
	"Chalk & Vermilion Fine Arts",
	"Chandler Tool",
	"Chanel, Inc.",
	"Charles Cook",
	"Charmed Creations LLC",
	"Chaz Dean Studio",
	"Chemsavers, Inc.",
	"Chevron Corporation",
	"Chief Architect, Inc.",
	"Chloé",
	"Chocolate Starfish Ltd.",
	"Chubby Chico Charms LLC",
	"classic-video",
	"Clayful Creations",
	"Cloanto IT srl",
	"CLOCHE COUTURE TRADEMARK",
	"Cloud B, Inc.",
	"Coach, Inc.",
	"Cocktailier LLC",
	"ColArt Americas, Inc.",
	"Coldwater Creek Inc.",
	"Collar and Cuffs London",
	"Colnago America, Inc.",
	"ColorMetrics LLC/ HairMarker LLC",
	"Comité Georges Mathieu",
	"Comité Champagne",
	"Competition Clutch",
	"Confederate Motorcycles LLC",
	"Continental Airlines",
	"Continental Enterprises",
	"Cool Mobility - Johanson Nominees Pty.",
	"Coquetry Clubwear",
	"CORE Survival, Inc.",
	"Cosanti Originals by Paolo Soleri",
	"Country Collectibles",
	"Coway Co., Ltd",
	"Cozy Glow Ltd.",
	"Craft-e-Creations",
	"Cranberry Card Company",
	"Crazy Aaron's Puttyworld (Crazy Aaron's Thinking Putty)",
	"Creative Carvings by Monte",
	"Creature Comforts Ltd dba Cornwall Stoneware Co.",
	"Creeks End Crochet",
	"Criswell Embroidery & Design",
	"Crochead Pty Ltd",
	"Crocs, Inc.",
	"Cucusoft, Inc.",
	"Cutco Cutlery Corporation",
	"Cutecolors.com",
	"Cynthia Dakin",
	"Cypress Collectibles",
	"Dais Enterprises",
	"Danes-R-Us Great Dane & Pet Art",
	"Daniel Bingham Design Studio",
	"Dansko, LLC",
	"Danworkshop.com",
	"Dark Horse Comics, Inc.",
	"DarkHorse Ranch, Inc.",
	"Dash America dba Pearl Izumi, Inc.",
	"Dassault Systemes S.A.",
	"data-professionals",
	"Dave Fant Company Of Arkansas Inc",
	"Dave's Discount Motors",
	"David Barton",
	"Davidson Photography",
	"DB Research L.L.P.",
	"Dedo Weigert Film GmbH",
	"Dell Computer Corp.",
	"Delorean Motor Company",
	"Delphi Technologies",
	"Delta Air Lines, Inc.",
	"DermalMedix",
	"Dermalogica, Inc.",
	"DESCO Corporation",
	"DFLK Inc.",
	"Dick Harrell Performance Center, Inc. ('DHPC Inc.') Licensing Department",
	"Diesel (London) Ltd.",
	"Digium, Inc.",
	"Dinnages (1989)",
	"Dionne Quintuplets, The",
	"DMS International",
	"Doctor's Associates Inc. dba Subway",
	"Doggie Bow Ties",
	'Dolby Laboratories Inc. ("Dolby")',
	"Dollar Shave Club",
	"Dongguan Hawson Jewelry",
	"DONMAR Enterprises, Inc. - SKYROOF®",
	"Don't Die, LLC",
	"Doria International, Inc.",
	"DPCD",
	"Dr. Denese - SkinScience Labs, Inc.",
	"Dr. Marty - Animal Ambassadors, LLC",
	"Drageekiss Ltd.",
	"DressThatMan.com",
	"Drive-In Exchange, Ltd",
	"DropCrate, LLC",
	"DSMB Partners, LLC DBA ActivatedYou",
	"DTX International",
	"Duke of Pearl, LLC",
	"Dunhill",
	"Dunlop Manufacturing, Inc.",
	"Duracell U.S. Operations, Inc.",
	"Dynamic Resource Group",
	"E.I. du Pont de Nemours and Company",
	"Eagle Creek Enterprises - Tim Cox Fine Art",
	"Eames Office - Lucia Eames",
	"Eason Media Ltd",
	"East Direct (UK) Ltd",
	"Easton Sports Inc.",
	"Eclipse Records, Inc.",
	"Ecosphere Associates, Inc.",
	"Edgar Rice Burroughs, Inc.",
	"Edison Nation",
	"EFI Live Limited Co.",
	"Electro-Harmonix Effects",
	"Ellison Educational Equipment, Inc. - Sizzix LLC",
	"Elope Inc.",
	"Ember Candles",
	"ENERGYbits Inc.",
	"Environ Skin Care Pty Ltd",
	"Epic Coolers",
	"Epson (UK) Corporation",
	"Ergo Baby Carrier, Inc.",
	"Erica Skadsen/Organic",
	"ESA - Entertainment Software Association",
	"Etienne Aigner AG",
	"etrailer.com",
	"Eurotech Photographics",
	"Exel Products",
	"EzyDog LLC",
	"Fab1Direct Ltd - Fablogix",
	"FabJob.com",
	"Fabriika",
	"Facelift Ent. Inc.",
	"Farmland Foods, Inc.",
	"Fashion Polish",
	"Fast Eddie's Vape Shop and Lounge, LLC",
	"FCA US, LLC",
	"FC Bayern München",
	"Federal Express Corporation (FedEx)",
	"Federation Against Copyright Theft (FACT) Ltd",
	"Fédération Internationale de Football Association (FIFA)",
	"Fender Musical Instruments Corporation",
	"Ferret Company",
	"FGM Ventures, LLC dba Petpost",
	"FileMaker, Inc.",
	"Fire Cam",
	"Fire House Neon LLC",
	"First Group / First Great Western",
	"Fishman",
	"Fit and Glow Inc.",
	"Fitness Brands Inc. / Direct Entertainment Media Group",
	"FJA Mods",
	"Fleurville Florida Council of Bromeliad Societies, Inc.",
	"Flexibrace",
	"Flowmaster",
	"Fluidity Enterprises, Inc.",
	"Footprints Publishings Inc.",
	"FourGreen Auto Parts",
	"Ford Motor Company",
	"FORMUFIT LLC",
	"Fort Worth Stock Show & Rodeo",
	"Foscam Intelligent Technology Co., Ltd.",
	"Foshan Shunde Shines E-Commerce Co., Ltd",
	"Fossil Reproductions",
	"Fossil, Inc.",
	"Fox (Twentieth Century Fox Film Corporation)",
	"Fretless Finger Guides",
	"Frantic Stamper, Inc.",
	"Frito-Lay, Inc.",
	"Fujikura Composites",
	"Funding USA LLC",
	"G. Loomis, Inc.",
	"Gaiam, Inc.",
	"Galiva Inc.",
	"Games 4 Hens Ltd",
	"Garden Selections Ltd.",
	"Garmin (UK)",
	"Garry Winogrand Photography",
	"Gaylord Entertainment Company",
	"General Motors",
	"Geneva Laboratories Ltd",
	"Georgia Pacific Corp.",
	"Georgie Girl Australia",
	"Gerber Childrenswear, LLC",
	"Getonfleek",
	"Giant UK LTD",
	"Gibson Brands, Inc.",
	"Gibson Performance Exhaust",
	"Giraffe Bath & Body, LLC",
	"Glenns Auto Repair and Performance LLC dba Glenns Auto Performance",
	"Global Healing Center",
	"GMV Productions",
	"GN Netcom, dba Jabra",
	"Goetze's Candy",
	"Go Nutrients",
	"Gorilla Tech LTD",
	"Gottlieb Development, LLC",
	"GQ Electronics",
	"Grand Chapter of Phi Sigma Kappa, Inc.",
	"Grand Lodge Fraternal Order of Police",
	"Grandma Moses Properties Company",
	"Graphics Technology HK Limited",
	"Graphite Design, Inc.",
	"Graydog Woodenware",
	"Great Bay Home",
	"Gretsch Company",
	"GrimmSpeed",
	"GUESS and MARCIANO Brands",
	"Gundry MD",
	"GUNNAR Optiks, LLC",
	"Guthy-Renker Corporation",
	"H&M",
	"Hair Flair LTD",
	"Harley-Davidson Motor Company",
	"Hartley Loudspeakers,Inc.",
	"HDMI Licensing, LLC",
	"Heirs and Estate of Peter William Ham",
	"Hells Angels Motorcycle Corporation Italia",
	"Herschel Supply Company Ltd.",
	"Hewlett-Packard Company (HP Ink & Toner)",
	"HIDS4U®",
	"High Island Health, LLC dba Aneros",
	"Hillstock Collection",
	"Himalaya Drug Company",
	"HK Wuppertal-Solingen-Remscheid",
	"HKS Europe Ltd",
	"Hoberman Designs",
	"Home Power, Inc.",
	"Hong Kong Proster Trading Limited",
	"Hook-Eze Pty Ltd",
	"Horizon Hobby, Inc.",
	"HotBuckles",
	"HouseLabels.com",
	"Huggalugs North America",
	"Huggaroo",
	"Hugs Not Drugs",
	"Human Touch, LLC",
	"Hy Cite Corporation",
	"Hybrid Systems Ltd., Inc. (HSL)",
	"Hydor Group",
	"IE WORKS, LLC",
	"iFixit",
	"Illume Holding Company LLC",
	"Incipio Technologies, Inc.",
	"Infinite Prosperity USA, LLC - Bluesky Travel Group Pty Ltd",
	"Inline Tube, Inc.",
	"Innovative JK Products LLC",
	"Innovative Salon Products, Inc. (LOMA)",
	"Innovative Textiles Inc.",
	"Insert Knowledge Here",
	"Intenze",
	"International Commercial Television - ICTV Brands",
	"Intuit, Inc.",
	"inVitamin, LLC",
	"IQ Implant Devices",
	"iRobot Corporation",
	"IronMind Enterprises, Inc.",
	"ISW Trading Pty. Ltd.",
	"It Works Marketing Compliance",
	"jackets4bikes",
	"Jaclin Dunne",
	"Jaguar & Land Rover",
	"James Andrew Grant",
	"Jayco (UK) Limited",
	"JEDirect Corp dba JETech Design",
	"Jemella Ltd",
	"Jenni Leigh Creations",
	"Jet Performance Products, Inc",
	"Jeweltailor Ltd.",
	"Jim Pace Magic",
	"JMDL Toys",
	"JNimports Ltd. dba Periea",
	"Jo Condrill",
	"John Deere",
	"Jordan Design",
	"Joseph Rorie",
	"Joy Kroeger Beckner, Classical Realism, from Hounds to Humans",
	"JRM Licensing",
	"JS&M Sales & Marketing Inc.",
	"JTY Imports/Exports Pty Ltd",
	"Juul, Inc.",
	"JuveTress",
	"K&M International, Inc. - Wild Republic",
	"K.W. Muth Company, Inc.",
	"Kai Z Feng Limited",
	"Kando Pictures Limited",
	"Kason Industries",
	"Kate Spade & Company",
	"KBA Enterprises LLC - Alban",
	"KE Health LLC, DBA BoriCap",
	"Kendama USA",
	"Kenrico Ltd.",
	"Kenu, Inc.",
	"KENVELO",
	"KeraFiber Europe Limited",
	"Kettle Foods Ltd",
	"Ketosource Ltd.",
	"Kikka Digga",
	"King Baby Studio",
	"King Technology, Inc.",
	"KiniArt Studios",
	"Klaire Labs",
	"Klasvsa (Huixian Dakang Electronic Commerce Co., Ltd.)",
	"Kleinn Automotive Accessories",
	"Knowledge In Motion, Inc.",
	"Kronemann Design Studio Pty. Ltd. - House of Kronemann USA",
	"Kun Shoulder Rest",
	"Kyser",
	"La Boutique de Bacchus",
	"La Chemise Lacoste SA",
	"Langley Productions, Inc.",
	"Larry Hartsell Seminars, Inc.",
	"Las Vegas Wranglers Professional Hockey Team",
	"Laser Design Int'l, LLC",
	"Lay-n-Go, LLC",
	"LCR Health",
	"Lenny and Eva, Inc.",
	"LetterRip Decals",
	"Leupold & Stevens, Inc.",
	"Level Terrain LLC dba FlipBelt",
	"Levi Strauss & Co.",
	"Lexmark International Inc.",
	"Lia Sophia Jewelery",
	"Liberta Co., Ltd. dba Baby Foot USA",
	"LifeProof - Treefrog",
	"Lifetrons Switzerland GmbH",
	"Lifted Research Group Inc. (L-R-G)",
	"Light & Dark Productions",
	"Linda McSweeney",
	"LinkedIn Corporation",
	"Lip Ink® International",
	"Lipsy Ltd",
	"Live Cell Research",
	"Lomo Industries Ltd.",
	"Longchamp",
	"Lori G Ashley",
	"Luxe Jewels, LLC dba Stella & Dot",
	"Luxe Purses",
	"LuxeAvant Innovations",
	"Mad Dogg Athletics, Inc.",
	"Magnet Shop",
	"Magnetic Poetry",
	"Magnolia Rubberstamps",
	"Makaton Charity",
	"Mamiya America Corporation",
	"Manchester United",
	"Manhattan Toy Company",
	"Mannatech Incorporated",
	"Marianne's Sol Mate Socks, Inc.",
	"Market Muncher LLC - Home Intuition",
	"Mars, Inc.",
	"Mary Capan",
	"Master of Illusions Entertainment",
	"Matt Groening",
	"Mavala International",
	"McCain Photography",
	"McGregor Fashion Group NV",
	"mDesign",
	"Medcosouth Healthcare, LLC",
	"Medieval Moccasins",
	"Mellotron Archives",
	"Melville Direct, LLC dba Bits and Pieces",
	"Mercantile Station 2",
	"Merle Norman Cosmetics, Inc.",
	"Metropolitan Kitchen",
	"MGA Entertainment, Inc. - A.B.C. International",
	"Microsoft",
	"Mike Barrett Productions Ltd.",
	"Mikimoto America",
	"Minelab Electronics",
	"Miniclip SA",
	"Ministero delle politiche agricole — ICQRF",
	"Ministry of Defense",
	"Miraflex S.A.",
	"Mitchell Repair Information Company",
	"Mocka Products Pty Ltd",
	"Mooneyes USA, Inc.",
	"Motion Picture Association of America (MPAA)",
	"Moviecraft Inc.",
	"Mud Puppy Mold Company",
	"Multipure Int'l",
	"Mutbak",
	"My Pageant Kid",
	"My Poupette Enterprises Inc.",
	"MyGift Enterprise LLC",
	"MyStudyGroup101",
	"Mywalit",
	"N.V.E., Inc.",
	"NailRENEW Corp.",
	"Nandita Arts",
	"National Academy of Television Arts & Sciences",
	"National Board of Medical Examiners - NBME®",
	"National Historic Mining Initiative LC3",
	"National Products Inc. DBA Ram Mounts",
	"National Shooting Sports Foundation",
	"Naturally Plus",
	"NCH Software",
	"NetPicks, LLC",
	"New Era Cap Company",
	"Nichols Photography",
	"Nickolas Muray Photo Archives, LLC",
	"Nike",
	"Nintendo of America Inc.",
	"Nissin Foods Holdings",
	"Niwot Corporation dba Specialty Products Company",
	"Noico",
	"Nomination S.R.L.",
	"Nordstrom, Inc.",
	"NSK Americas, Inc.",
	"Nu Skin International Inc.",
	"Nucific",
	"NUTRAFOL - Nutraceutical Wellness, Inc.",
	"Nutramax Laboratories, Inc.",
	"Oakley, Inc.",
	"Oki Data Corporation",
	"Öko-Tex",
	"Old & Urban",
	"One Two Cosmetics, LLC",
	"One Wise Mac Limited",
	"OnlineFabricStore",
	"Open University",
	"OPI Products, Inc",
	"Orange USA",
	"Organo Gold",
	"Orielle, LLC",
	"Origami Owl, LLC",
	"Orthotebb Health Shoes, LLC",
	"Osmosis Skincare",
	"Osnat",
	"Otterbox",
	"Overstock.com Inc.",
	"P Rogers, Inc.",
	"Pacific Market International, LLC",
	"Packard Club",
	"Paddington and Company Limited",
	"Pagedown Technology, LLC",
	"Pamp SA",
	"Pampered Chef, The",
	"Panasonic Corporation of North America",
	"Paradise Film Institute/Big Pictures",
	"Pasoday Products Ltd",
	"Patch Collection, LLC",
	"Patch Me Thru",
	"Patchexpertsus",
	"Patmont Motor Werks/Go-Ped®",
	"Pawsitively Perfect Bows",
	"PeachpopsClipArt™",
	"Peak Coffee Ltd",
	"Pen Press Publishing",
	"Peppadew International",
	"Peri K Designs",
	"Pevonia International, LLC",
	"Philosophy, Inc.",
	"Phiten GmbH",
	"Photomedex",
	"PiperWai, LLC",
	"Plans Designs",
	"Plarium Global LTD",
	"Platinum Place",
	"Platypus Wear, Inc. dba Bad Boy Brands",
	"Playboy Enterprises",
	"Playtex Products, LLC",
	"Plexaderm",
	"Plexus Worldwide, Inc",
	"Ploom - Pax Labs",
	"Plumeria Bay, Inc.",
	"Pneumatic Components Ltd",
	"Pocket Radar, Inc.",
	"Polymorphe, Inc",
	"Pool Cover Corp. dba Loop Loc",
	"Poppy Company",
	"PopSockets LLC",
	"Portage Word-Wide, Inc. - Manhattan Portage",
	"Power Art Design Airbrushs Pty Ltd",
	"Power Straight",
	"PowerPortLA, LLC",
	"Practically Darling Designs",
	"Prada S.A.",
	"Pratico Goods, LLC",
	"Premier League",
	"PremiumFishing Auctions Store",
	"Prescott Plastics, LLC",
	"Princeton Nutrients",
	"Proactiv Company Sárl",
	"Probiotic America",
	"Procter & Gamble",
	"ProfessorProfits.com",
	"ProFroster",
	"Pronto Moda Global Limited",
	"Provo Craft & Novelty, Inc.",
	"Purdey",
	"Quane Cosmetics",
	"Quanovate Tech, Inc. - Mira",
	"Quiksilver, Inc",
	"Rachel Caine",
	"Radiancy, Inc.",
	"Radio Flyer, Inc.",
	"Rainbow Sandals, Inc.",
	"Ram Cleaner",
	"Randomwalk, LLC",
	"Ranger Doug's Enterprises",
	"Rare Sportsfilms Inc.",
	"Rasasi Perfumes",
	"Ray-Ban",
	"Rayverstar LLC",
	"Razormaid! Productions",
	"RC Williams Company",
	"RE/MAX International, Inc.",
	"Rea.Deeming Beauty, Inc. dba Beautyblender",
	"Red Bull GmbH",
	"Red Digital Cinema Camera Company",
	"Red Camel Racing Ltd.",
	"Red Hat Society, Inc.",
	"Red Monkey Designs, Inc.",
	"Red Steagall's Cowboy Corner",
	"Relix International, Inc.",
	"Relleciga Official",
	"Rembrandt Charms",
	"ReminderBand Inc.",
	"Remote Pro Pty Ltd",
	"Reshoevn8r",
	"Revelation Records",
	"Revitalash Cosmetics",
	"RGK Innovations LLC",
	"Rhodes International",
	"Richard Avedon Foundation",
	"Rideworx Pty Ltd.",
	"Ridgerock Tools",
	"Right Deals UK Limited",
	"Rivington Designs Ltd",
	"RN Study Spot",
	"Rocket Science Institute, Inc.",
	"Rodan + Fields",
	"Rohde Fine Art",
	"Rolls-Royce",
	"Rondofile",
	"Rosetta Stone (UK) Ltd",
	"Roth Company",
	"Rothstein Guitars",
	"Rowena Cherry",
	"Royal British Legion, The",
	"Royal Silk LTD",
	"RRO Entertainment",
	"Rude Awakening Coffee House",
	"Ryohin Keikaku Co.,Ltd. - Muji",
	"Sacem",
	"Sado Nation",
	"Sadowsky Guitars Ltd.",
	"Sakura Color Products of America, Inc.",
	"Saleen",
	"Salt Gems LLC",
	"Salt Life Holdings, LLC",
	"SaltWorks, Inc.",
	"Santas Christmas Town",
	"Sanyo Electric Co., Ltd.",
	"SAP",
	"Susan Lough",
	"Sara Moon",
	"Savanna Group LTD - Savanna Samson",
	"Savvy Turtle Inc",
	"ScanTool.net, LLC",
	"Schlyer Designs",
	"Scottcrew Enterprises",
	"SD Biotechnologies",
	"Searching for Louis Media",
	"Secret-of-Art",
	"Seeing with Sound - The vOICe",
	"Sensation Press",
	"Sensual Candle",
	"Sew Terific Designs",
	"Sewing Bee Crinoline Ladies Embroidery Patterns",
	"Shabby Chic",
	"Sheridan Douglas Press",
	"Shimano, Inc",
	"SEISCO International Limited",
	"Shewee Ltd",
	"Shiseido Company Limited",
	"Shop Vac Corporation",
	"Sigma Beauty",
	"Sigmacumlaude.com",
	"Simon Carey",
	"Simpler Trading, LLC",
	"Sinister Mfg. Co., Inc. (Sinister Diesel)",
	"Siser",
	"Skiboards Superstore, Inc.",
	"Sky Deutschland Fernsehen GmbH & Co. KG",
	"SmarterFresh, LLC",
	"SmartSound Software, Inc.",
	"SMS Audio, LLC",
	"SnakeEmporium.com",
	"Snap-on Incorporated",
	"SnugglyCat Inc - The Ripple Rug",
	"Society for Human Resource Management",
	"SockDock, LLC",
	"SoClean, Inc.",
	"Software & Information Industry Association (SIIA)",
	"Sole Technology, Inc.",
	"SoloWork Studio",
	"Sony Ericsson Mobile Communications AB",
	"Southwest Pictures / Southwest Entertainment Group, LLC",
	"SpiceFit",
	"Spicer Pro, LLC",
	"Sprint Corporation",
	"Spyder Active Sports, Inc.",
	"Standard Innovation Corporation",
	"Star Alliance Services GmbH",
	"Stephen Shore, photographs",
	"Stromberg Carburetor Ltd.",
	"STS Industries Inc. - NageBee",
	"Stussy Inc.",
	"STV Motorsports LLC",
	"Sue Coffee",
	"Sugru (FormFormForm Ltd)",
	"SummitFashions",
	"Suncast Corporation",
	"Sunrider International",
	"Supacaz",
	"Superior Products USA LLC",
	"Surgi Corp",
	"Surgical Appliance Industries, Inc.",
	"SuZhou Aobani Trading Company Ltd.",
	"Swanson Health Products",
	"Swarovski North America Limited",
	"Swift Response, LLC",
	"Swing Set Stuff",
	"Swiss Army Brands, Inc.",
	"Sylver Designs",
	"Symantec",
	"Synergetics",
	"Tactical Beard Owners Club (TBOC)",
	"Tad-Bits Baby Items and More LLC",
	"Takata Corporation",
	"Tamiya America, Inc.",
	"Tania R. Chase",
	"TASER International Inc.",
	"Team Mysterio, Inc.",
	"Teami Blends",
	"Technica USA (Moon Boot)",
	"Technical Video, LLC",
	"Technopack Corporation (Jorestech)",
	"TechSmith Corporation",
	"Tecscan of North Florida, Inc.",
	"Tekay Designs Inc.",
	"That's Greenius, LLC",
	"The Himalaya Drug Company",
	"The Jewelry Channel Inc. dba Shop LC",
	"The Juice Plus+ Company",
	"The LifeVantage Corporation",
	"The Richemont Group",
	"Thea Gouverneur BV",
	"These Please Ltd",
	"Things 4 Strings LLC",
	"Third Man Records",
	"Thomas Losh",
	"ThreadABead",
	"Three Dogs and a Cat Inc.",
	"TidyEmu",
	"Tiffany & Company",
	"Tiger Tom Pistone Race Cars & Parts",
	"TigerDirect",
	"Time Tracker Technology",
	"TMH Technology Co., Ltd.",
	"To Your Home Ltd",
	"Tokentools Pty Ltd",
	"TokyoFlash Japan",
	"Tom Kelley Studios, Inc.",
	"Tomei Powered USA Inc.",
	"Tommy Hilfiger Licensing BV",
	"Top Secret Recipes",
	"Tori Richard, Ltd.",
	"Total Family Ministries",
	"Total Gym",
	"Tottenham Hotspur Ltd",
	"ToughCOINS LLC",
	"TrailerSauce",
	"Trainingmask, LLC",
	"Treasured Hungarian Family Recipes TM",
	"Tshirt Bordello",
	"Turbosmart",
	"TÜV Markenverbund e.V",
	"Tüv Süd",
	"Twinkl Ltd",
	"UGG Holdings, Inc.",
	"UGS Corp.",
	"Ultimate Creations, Inc. / Ultimate Warrior / Warrior",
	"Ultimate Sports Franchise Agents",
	"Ultimate Pet Nutrition, LLC",
	"Ultra Glow Cosmetics LTD",
	"Ultramax Products Limited",
	"Umbro International Limited",
	"Underwriters Laboratories, Inc.",
	"Uni-Trend Technology Co., Ltd",
	"United States Forest Service - USDA",
	"University of Iowa",
	"Ursula Hock-Henschke",
	"Vacheron Constantin",
	"Vale Science Technology Co. Ltd",
	"Van Cleef & Arpels",
	"Vanguard Industries, Inc.",
	"Velcro Companies",
	"Vera Bradley",
	"Versace",
	"Vickie Milazzo Institute",
	"Victory Seed Co.",
	"Vietnam International Video",
	"Vintage Cigarette Lighters",
	"Vintage Fans, L.L.C.",
	"Viper Interactive",
	"Virgil C. Stephens",
	"Vitagene, Inc",
	"Vivint, Inc.",
	"VKR Holding A/S (VELUX)",
	"Volkswagen Corporation",
	"Vortex Optics",
	"Walker Metalsmiths Celtic Jewelry",
	"Walnut Studiolo LLC",
	"Ware Family Genealogy",
	"Warner Music Group",
	"Warner's Blue Ribbon Books on Swarovski",
	"Water Pik, Inc",
	"Wax Liquidizer Ltd.",
	"WD Music Products, Inc.",
	"Weinstein Company, The",
	"West American Corporation d/b/a RBH Sound",
	"West Frames, Inc.",
	"WH Software Limited",
	"Whelen Engineering Company, Inc.",
	"Whizardries, Inc.",
	"Whole Body Research, LLC",
	"Wiggles Touring Pty Limited, The",
	"Windmill-Parts.com",
	"Wisdom of the Ages",
	"With You Designs, LLC and With You Lockets",
	"Wonder Wizards",
	"World Hockey Association, LLC",
	"World Wrestling Entertainment, Inc. (WWE)",
	"Worldwide Women Artists (WWAO)",
	"WristWidget",
	"Würth Srl",
	"X Bats",
	"XBMC Solutions Ltd - Droidbox",
	"Xiangzhiheng Electronics Inc.",
	"X-mini Capsule Speakers",
	"XPressMart.com",
	"Y&T - Meniketti",
	"Yamaha Corporation of America",
	"Yogitoes",
	"Younghair AB LTD",
	"Younique, LLC",
	"Your Baby Can, LLC.",
	"Yubo Technology Co.Ltd.",
	"Yum! Brands, Inc.",
	"Yvonne Hedley",
	"Z Produx Inc.",
	"Z-Man Fishing Products, Inc.",
	"ZAGG",
	"Zamboni",
	"Zappos.com",
	"Zen Design Group Ltd",
	"Zephyr Vaporizers",
];
