const veroListOld = [
	"3M Company",
	"3Skulls Paintball",
	"AAT - The Association of Acounting Technicians",
	"Abercrombie & Fitch",
	"Action Mining Services Inc.",
	"Adobe",
	"ADT",
	"Air Force One Air Conditioning",
	"Aircraft Technical Publishers",
	"Alaska Airlines",
	"Aleratec, Inc.",
	"Alex Perez",
	"Alfresco Heating",
	"ALIENTECH SRL",
	"All Saints (Retail) Ltd",
	"ALM Productions",
	"Aloe of America, Inc. & Forever Living Products Int'l.",
	"Amari Bliss",
	"AMC Photographics Limited",
	"Americana International Ltd.",
	"American Eagle Outfitters",
	"American Weigh Scales, Inc.",
	"American Welding Society",
	"Americas Drive-In Corp. / Sonic Corp. & Subsidiaries",
	"Amiclubwear.com",
	"Amway Corporation (US)",
	"Amybug's Attic",
	"AnalogMan Guitar Effects",
	"Andrew James Worldwide",
	"Andy Thomas",
	"Angela LaFramboise",
	"Annenberg Media",
	"Ansonia Records, Inc.",
	"Anvil Forge Art",
	"Apex Tool Group",
	"AQUALIBRA UK",
	"AR15.com",
	"Arduino, LLC",
	"ARIIX, LLC",
	"Artbeats Software, Inc.",
	"Arturia",
	"Ashleigh Talbot",
	"AsKoruBeads",
	"Atlantic Research and Marketing (A.R.M.S.)",
	"Atvimports",
	"Auntie Anne's, Inc.",
	"Austin City Limits/KLRU",
	"Australian Gold, Inc.",
	"Australian Made Campaign Limited",
	"Authentic Brands Group LLC",
	"Autism Speaks, Inc.",
	"Autodata Limited",
	"Auto Meter Products, Inc. (Autometer)",
	"Autoline Industries",
	"Automotive Technologies, Inc.",
	"Avedis Zildjian, Co.",
	"B&M Racing",
	"B. C. Broncos",
	"B.H.P., Inc. dba Nialaya Jewelry",
	"Bad Monkey Productions",
	"Bally Pinball Fun",
	"Barnett Research and Computer Imaging",
	"Barstool Sports, Inc.",
	"Baume & Mercier",
	"Beachbody, LLC",
	"Bed Band Store",
	"Bell Helicopter Textron Inc.",
	"Benchmade Knife Company, Inc.",
	"Beyond Cell",
	"Beverly Hills MD",
	"Bill Lawrence Products",
	"Bill Owen-Cowboy Artist",
	"Billie W. Taylor II, Ph.D.",
	"BINO Products, LLC",
	"Biotrade Bulgaria Ltd.",
	"BioTrust Nutrition",
	"BISSELL Homecare, Inc.",
	"Bittrex, Inc.",
	"Blackpoint Engineering, LLC",
	"Blitzburgh Sports",
	"Blockware, LLC dba Great Useful Stuff",
	"Bloomberg L.P.",
	"BlossomSugarArt",
	"Bluetooth",
	"Bombardier Recreational Products, Inc.",
	"Bonnie's Plants",
	"Boppy Company, The",
	"Bose Corporation",
	"Botanissa LLC - See U Baby",
	"Boveda, Inc.",
	"Brenda Franklin",
	"Brian Smith",
	"Bridgestone Brands, LLC",
	"Brisant Secure Ltd",
	"British Phonographic Industry Limited",
	"Bronze Gallery",
	"Browning Laboratories, Inc.",
	"Bruce Lee Enterprises",
	"Bua, Inc.",
	"Buck Knives, Inc.",
	"Bug Me Video Inc.",
	"Bumbleride Inc.",
	"Burberry Limited",
	"Burlen Fuel System Limited",
	"Bushnell Performance Optics and Tasco Sales Pty Ltd.",
	"Business Software Alliance (EU)",
	"Bwthynbach",
	"Calutech, Inc.",
	"Canadian Standards Association",
	"Canon, Inc.",
	"Canyon Chenille, Inc.",
	"Canyon Dancer Motorcycle Products",
	"Care Creations, Inc.",
	"Car-Freshner Corporation",
	"Carl McCoy (Fields of the Nephilim)",
	"Carlstar Group â€“ ITP and Carlisle Brands",
	"Carmen's Vintage Collections",
	"Carmix-GPS",
	"Carrs Coins and Rocks, Inc.",
	"Cartier",
	"CBS Entertainment and Desilu, too, LLC (Unforgettable Licensing)",
	"CBT Nuggets, Inc",
	"CeraNet, Inc.",
	"Chalk & Vermilion Fine Arts",
	"Chanel, Inc.",
	"Charles Cook",
	"Chaz Dean Studio",
	"Chemsavers, Inc.",
	"Chevron Corporation",
	"Chief Architect, Inc.",
	"ChloÃ©",
	"Chocolate Starfish Ltd.",
	"Chubby Chico Charms LLC",
	"classic-video",
	"Clayful Creations",
	"Cloanto IT srl",
	"CLOCHE COUTURE TRADEMARK",
	"Cloud B, Inc.",
	"Coach, Inc.",
	"Cocktailier LLC",
	"ColArt Americas, Inc.",
	"Coldwater Creek Inc.",
	"Collar and Cuffs London",
	"Colnago America, Inc.",
	"ColorMetrics LLC/ HairMarker LLC",
	"ComitÃ© Georges Mathieu",
	"ComitÃ© Champagne",
	"Competition Clutch",
	"Continental Airlines",
	"Continental Enterprises",
	"Cool Mobility - Johanson Nominees Pty.",
	"Coquetry Clubwear",
	"Cosanti Originals by Paolo Soleri",
	"Country Collectibles",
	"Coway Co., Ltd",
	"Cozy Glow Ltd.",
	"Craft-e-Creations",
	"Cranberry Card Company",
	"Crazy Aaron's Puttyworld (Crazy Aaron's Thinking Putty)",
	"Creative Carvings by Monte",
	"Creature Comforts Ltd dba Cornwall Stoneware Co.",
	"Creeks End Crochet",
	"Criswell Embroidery & Design",
	"Crocs, Inc.",
	"Cucusoft, Inc.",
	"Cutco Cutlery Corporation",
	"Cutecolors.com",
	"Cynthia Dakin",
	"Cypress Collectibles",
	"Dais Enterprises",
	"Danes-R-Us Great Dane & Pet Art",
	"Daniel Bingham Design Studio",
	"Dansko, LLC",
	"Danworkshop.com",
	"Dark Horse Comics, Inc.",
	"DarkHorse Ranch, Inc.",
	"Dash America dba Pearl Izumi, Inc.",
	"Dassault Systemes S.A.",
	"data-professionals",
	"Dave Fant Company Of Arkansas Inc",
	"Dave's Discount Motors",
	"David Barton",
	"Davidson Photography",
	"DB Research L.L.P.",
	"Dedo Weigert Film GmbH",
	"Dell Computer Corp.",
	"Delphi Technologies",
	"Delta Air Lines, Inc.",
	"DermalMedix",
	"Dermalogica, Inc.",
	"DFLK Inc.",
	"Dick Harrell Performance Center, Inc. ('DHPC Inc.') Licensing Department",
	"Diesel (London) Ltd.",
	"Digium, Inc.",
	"Dinnages (1989)",
	"Dionne Quintuplets, The",
	"DMS International",
	"Doctor's Associates Inc. dba Subway",
	"Doggie Bow Ties",
	'Dolby Laboratories Inc. ("Dolby")',
	"Dollar Shave Club",
	"Dongguan Hawson Jewelry",
	"DONMAR Enterprises, Inc. - SKYROOFÂ®",
	"Don't Die, LLC",
	"Doria International, Inc.",
	"DPCD",
	"Dr. Denese - SkinScience Labs, Inc.",
	"Drageekiss Ltd.",
	"DressThatMan.com",
	"Drive-In Exchange, Ltd",
	"DropCrate, LLC",
	"DSMB Partners, LLC DBA ActivatedYou",
	"DTX International",
	"Duke of Pearl, LLC",
	"Dunhill",
	"Dunlop Manufacturing, Inc.",
	"Duracell U.S. Operations, Inc.",
	"Dynamic Resource Group",
	"E.I. du Pont de Nemours and Company",
	"Eagle Creek Enterprises - Tim Cox Fine Art",
	"Eames Office - Lucia Eames",
	"Eason Media Ltd",
	"East Direct (UK) Ltd",
	"Easton Sports Inc.",
	"Eclipse Records, Inc.",
	"Ecosphere Associates, Inc.",
	"Edgar Rice Burroughs, Inc.",
	"Edison Nation",
	"EFI Live Limited Co.",
	"Electro-Harmonix Effects",
	"Elope Inc.",
	"Ember Candles",
	"ENERGYbits Inc.",
	"Environ Skin Care Pty Ltd",
	"Epic Coolers",
	"Epson (UK) Corporation",
	"Ergo Baby Carrier, Inc.",
	"Erica Skadsen/Organic",
	"ESA - Entertainment Software Association",
	"Etienne Aigner AG",
	"etrailer.com",
	"Eurotech Photographics",
	"Exel Products",
	"EzyDog LLC",
	"Fab1Direct Ltd - Fablogix",
	"FabJob.com",
	"Fabriika",
	"Facelift Ent. Inc.",
	"Farmland Foods, Inc.",
	"Fashion Polish",
	"Fast Eddie's Vape Shop and Lounge, LLC",
	"FCA US, LLC",
	"FC Bayern MÃ¼nchen",
	"Federal Express Corporation (FedEx)",
	"Federation Against Copyright Theft (FACT) Ltd",
	"FÃ©dÃ©ration Internationale de Football Association (FIFA)",
	"Fender Musical Instruments Corporation",
	"Ferret Company",
	"FGM Ventures, LLC dba Petpost",
	"FileMaker, Inc.",
	"Fire Cam",
	"Fire House Neon LLC",
	"First Group / First Great Western",
	"Fishman",
	"Fitness Brands Inc. / Direct Entertainment Media Group",
	"FJA Mods",
	"Fleurville Florida Council of Bromeliad Societies, Inc.",
	"Flexibrace",
	"Flowmaster",
	"Fluidity Enterprises, Inc.",
	"Footprints Publishings Inc.",
	"Ford Motor Company",
	"FORMUFIT LLC",
	"Fort Worth Stock Show & Rodeo",
	"Foscam Intelligent Technology Co., Ltd.",
	"Foshan Shunde Shines E-Commerce Co., Ltd",
	"Fossil Reproductions",
	"Fossil, Inc.",
	"Fox (Twentieth Century Fox Film Corporation)",
	"Fretless Finger Guides",
	"Frantic Stamper, Inc.",
	"Frito-Lay, Inc.",
	"Fujikura Composites",
	"Funding USA LLC",
	"G. Loomis, Inc.",
	"Gaiam, Inc.",
	"Galiva Inc.",
	"Games 4 Hens Ltd",
	"Garden Selections Ltd.",
	"Garmin (UK)",
	"Garry Winogrand Photography",
	"Gaylord Entertainment Company",
	"General Motors",
	"Geneva Laboratories Ltd",
	"Georgia Pacific Corp.",
	"Georgie Girl Australia",
	"Gerber Childrenswear, LLC",
	"Getonfleek",
	"Giant UK LTD",
	"Gibson Brands, Inc.",
	"Gibson Performance Exhaust",
	"Giraffe Bath & Body, LLC",
	"Glenns Auto Repair and Performance LLC dba Glenns Auto Performance",
	"GMV Productions",
	"GN Netcom, dba Jabra",
	"Go Nutrients",
	"Gorilla Tech LTD",
	"Gottlieb Development, LLC",
	"GQ Electronics",
	"Grand Chapter of Phi Sigma Kappa, Inc.",
	"Grand Lodge Fraternal Order of Police",
	"Grandma Moses Properties Company",
	"Graphics Technology HK Limited",
	"Graphite Design, Inc.",
	"Graydog Woodenware",
	"Gretsch Company",
	"GrimmSpeed",
	"GUESS and MARCIANO Brands",
	"Gundry MD",
	"GUNNAR Optiks, LLC",
	"Guthy-Renker Corporation",
	"H&M",
	"Hair Flair LTD",
	"Harley-Davidson Motor Company",
	"Hartley Loudspeakers,Inc.",
	"HDMI Licensing, LLC",
	"Heirs and Estate of Peter William Ham",
	"Hells Angels Motorcycle Corporation Italia",
	"Herschel Supply Company Ltd.",
	"Hewlett-Packard Company (HP Ink & Toner)",
	"HIDS4UÂ®",
	"High Island Health, LLC dba Aneros",
	"Hillstock Collection",
	"Himalaya Drug Company",
	"HK Wuppertal-Solingen-Remscheid",
	"HKS Europe Ltd",
	"Hoberman Designs",
	"Home Power, Inc.",
	"Hook-Eze Pty Ltd",
	"Horizon Hobby, Inc.",
	"HotBuckles",
	"HouseLabels.com",
	"Huggalugs North America",
	"Hugs Not Drugs",
	"Human Touch, LLC",
	"Hy Cite Corporation",
	"Hybrid Systems Ltd., Inc. (HSL)",
	"Hydor Group",
	"IE WORKS, LLC",
	"iFixit",
	"Illume Holding Company LLC",
	"Incipio Technologies, Inc.",
	"Infinite Prosperity USA, LLC - Bluesky Travel Group Pty Ltd",
	"Inline Tube, Inc.",
	"Innovative JK Products LLC",
	"Innovative Salon Products, Inc. (LOMA)",
	"Innovative Textiles Inc.",
	"Insert Knowledge Here",
	"Intenze",
	"International Commercial Television - ICTV Brands",
	"Intuit, Inc.",
	"inVitamin, LLC",
	"IQ Implant Devices",
	"iRobot Corporation",
	"It Works Marketing Compliance",
	"jackets4bikes",
	"Jaclin Dunne",
	"Jaguar & Land Rover",
	"James Andrew Grant",
	"Jayco (UK) Limited",
	"JEDirect Corp dba JETech Design",
	"Jemella Ltd",
	"Jenni Leigh Creations",
	"Jet Performance Products, Inc",
	"Jeweltailor Ltd.",
	"Jim Pace Magic",
	"JMDL Toys",
	"JNimports Ltd. dba Periea",
	"Jo Condrill",
	"John Deere",
	"Jordan Design",
	"Joseph Rorie",
	"Joy Kroeger Beckner, Classical Realism, from Hounds to Humans",
	"JRM Licensing",
	"JS&M Sales & Marketing Inc.",
	"JTY Imports/Exports Pty Ltd",
	"Juul, Inc.",
	"JuveTress",
	"K&M International, Inc. - Wild Republic",
	"K.W. Muth Company, Inc.",
	"Kai Z Feng Limited",
	"Kando Pictures Limited",
	"Kason Industries",
	"Kate Spade & Company",
	"KBA Enterprises LLC - Alban",
	"KE Health LLC, DBA BoriCap",
	"Kendama USA",
	"Kenu, Inc.",
	"KENVELO",
	"KeraFiber Europe Limited",
	"Kettle Foods Ltd",
	"Ketosource Ltd.",
	"Kikka Digga",
	"King Baby Studio",
	"King Technology, Inc.",
	"KiniArt Studios",
	"Klasvsa (Huixian Dakang Electronic Commerce Co., Ltd.)",
	"Kleinn Automotive Accessories",
	"Knowledge In Motion, Inc.",
	"Kronemann Design Studio Pty. Ltd. - House of Kronemann USA",
	"Kun Shoulder Rest",
	"Kyser",
	"La Boutique de Bacchus",
	"La Chemise Lacoste SA",
	"Langley Productions, Inc.",
	"Larry Hartsell Seminars, Inc.",
	"Las Vegas Wranglers Professional Hockey Team",
	"Laser Design Int'l, LLC",
	"LCR Health",
	"Lenny and Eva, Inc.",
	"LetterRip Decals",
	"Leupold & Stevens, Inc.",
	"Levi Strauss & Co.",
	"Lexmark International Inc.",
	"Lia Sophia Jewelery",
	"LifeProof - Treefrog",
	"Lifetrons Switzerland GmbH",
	"Lifted Research Group Inc. (L-R-G)",
	"Light & Dark Productions",
	"Linda McSweeney",
	"LinkedIn Corporation",
	"Lip InkÂ® International",
	"Lipsy Ltd",
	"Live Cell Research",
	"Lomo Industries Ltd.",
	"Longchamp",
	"Lori G Ashley",
	"Luxe Jewels, LLC dba Stella & Dot",
	"Luxe Purses",
	"Mad Dogg Athletics, Inc.",
	"Magnet Shop",
	"Magnetic Poetry",
	"Magnolia Rubberstamps",
	"Makaton Charity",
	"Mamiya America Corporation",
	"Manchester United",
	"Mannatech Incorporated",
	"Marianne's Sol Mate Socks, Inc.",
	"Mars, Inc.",
	"Mary Capan",
	"Master of Illusions Entertainment",
	"Matt Groening",
	"Mavala International",
	"McCain Photography",
	"McGregor Fashion Group NV",
	"mDesign",
	"Medcosouth Healthcare, LLC",
	"Medieval Moccasins",
	"Mellotron Archives",
	"Melville Direct, LLC dba Bits and Pieces",
	"Mercantile Station 2",
	"Merle Norman Cosmetics, Inc.",
	"Metropolitan Kitchen",
	"MGA Entertainment, Inc. - A.B.C. International",
	"Microsoft",
	"Mike Barrett Productions Ltd.",
	"Mikimoto America",
	"Minelab Electronics",
	"Miniclip SA",
	"Ministero delle politiche agricole â€” ICQRF",
	"Ministry of Defense",
	"Miraflex S.A.",
	"Mitchell Repair Information Company",
	"Mocka Products Pty Ltd",
	"Mooneyes USA, Inc.",
	"Motion Picture Association of America (MPAA)",
	"Moviecraft Inc.",
	"Mud Puppy Mold Company",
	"Multipure Int'l",
	"Mutbak",
	"My Pageant Kid",
	"My Poupette Enterprises Inc.",
	"MyGift Enterprise LLC",
	"MyStudyGroup101",
	"Mywalit",
	"N.V.E., Inc.",
	"Nandita Arts",
	"National Academy of Television Arts & Sciences",
	"National Board of Medical Examiners - NBMEÂ®",
	"National Historic Mining Initiative LC3",
	"National Products Inc. DBA Ram Mounts",
	"National Shooting Sports Foundation",
	"Naturally Plus",
	"NCH Software",
	"NetPicks, LLC",
	"New Era Cap Company",
	"Nichols Photography",
	"Nickolas Muray Photo Archives, LLC",
	"Nike",
	"Nintendo of America Inc.",
	"Nissin Foods Holdings",
	"Niwot Corporation dba Specialty Products Company",
	"Noico",
	"Nomination S.R.L.",
	"Nordstrom, Inc.",
	"NSK Americas, Inc.",
	"Nu Skin International Inc.",
	"Nucific",
	"Nutramax Laboratories, Inc.",
	"Oakley, Inc.",
	"Oki Data Corporation",
	"Ã–ko-Tex",
	"Old & Urban",
	"One Wise Mac Limited",
	"OnlineFabricStore",
	"Open University",
	"OPI Products, Inc",
	"Orange USA",
	"Organo Gold",
	"Orielle, LLC",
	"Origami Owl, LLC",
	"Orthotebb Health Shoes, LLC",
	"Osmosis Skincare",
	"Osnat",
	"Otterbox",
	"Overstock.com Inc.",
	"P Rogers, Inc.",
	"Pacific Market International, LLC",
	"Packard Club",
	"Paddington and Company Limited",
	"Pagedown Technology, LLC",
	"Pamp SA",
	"Pampered Chef, The",
	"Panasonic Corporation of North America",
	"Paradise Film Institute/Big Pictures",
	"Pasoday Products Ltd",
	"Patch Me Thru",
	"Patchexpertsus",
	"Patmont Motor Werks/Go-PedÂ®",
	"Pawsitively Perfect Bows",
	"PeachpopsClipArtâ„¢",
	"Peak Coffee Ltd",
	"Pen Press Publishing",
	"Peri K Designs",
	"Pevonia International, LLC",
	"Philosophy, Inc.",
	"Phiten GmbH",
	"Photomedex",
	"PiperWai, LLC",
	"Plans Designs",
	"Platinum Place",
	"Platypus Wear, Inc. dba Bad Boy Brands",
	"Playboy Enterprises",
	"Playtex Products, LLC",
	"Plexaderm",
	"Plexus Worldwide, Inc",
	"Ploom - Pax Labs",
	"Plumeria Bay, Inc.",
	"Pneumatic Components Ltd",
	"Polymorphe, Inc",
	"Pool Cover Corp. dba Loop Loc",
	"Poppy Company",
	"PopSockets LLC",
	"Portage Word-Wide, Inc. - Manhattan Portage",
	"Power Art Design Airbrushs Pty Ltd",
	"Power Straight",
	"PowerPortLA, LLC",
	"Practically Darling Designs",
	"Prada S.A.",
	"Pratico Goods, LLC",
	"Premier League",
	"PremiumFishing Auctions Store",
	"Princeton Nutrients",
	"Proactiv Company SÃ¡rl",
	"Probiotic America",
	"Procter & Gamble",
	"ProfessorProfits.com",
	"ProFroster",
	"Pronto Moda Global Limited",
	"Provo Craft & Novelty, Inc.",
	"Purdey",
	"Quane Cosmetics",
	"Quiksilver, Inc",
	"Rachel Caine",
	"Radiancy, Inc.",
	"Radio Flyer, Inc.",
	"Rainbow Sandals, Inc.",
	"Randomwalk, LLC",
	"Ranger Doug's Enterprises",
	"Rare Sportsfilms Inc.",
	"Rasasi Perfumes",
	"Ray-Ban",
	"Rayverstar LLC",
	"Razormaid! Productions",
	"RE/MAX International, Inc.",
	"Rea.Deeming Beauty, Inc. dba Beautyblender",
	"Red Bull GmbH",
	"Red Digital Cinema Camera Company",
	"Red Camel Racing Ltd.",
	"Red Hat Society, Inc.",
	"Red Monkey Designs, Inc.",
	"Red Steagall's Cowboy Corner",
	"Relix International, Inc.",
	"Relleciga Official",
	"Rembrandt Charms",
	"ReminderBand Inc.",
	"Remote Pro Pty Ltd",
	"Reshoevn8r",
	"Revelation Records",
	"Revitalash Cosmetics",
	"RGK Innovations LLC",
	"Rhodes International",
	"Richard Avedon Foundation",
	"Rideworx Pty Ltd.",
	"Ridgerock Tools",
	"Right Deals UK Limited",
	"Rivington Designs Ltd",
	"RN Study Spot",
	"Rocket Science Institute, Inc.",
	"Rodan",
	"Fields",
	"Rohde Fine Art",
	"Rolls-Royce",
	"Rosetta Stone (UK) Ltd",
	"Roth Company",
	"Rothstein Guitars",
	"Rowena Cherry",
	"Royal British Legion, The",
	"Royal Silk LTD",
	"RRO Entertainment",
	"Rude Awakening Coffee House",
	"Sacem",
	"Sado Nation",
	"Sadowsky Guitars Ltd.",
	"Sakura Color Products of America, Inc.",
	"Saleen",
	"Salt Gems LLC",
	"Salt Life Holdings, LLC",
	"SaltWorks, Inc.",
	"Santas Christmas Town",
	"Sanyo Electric Co., Ltd.",
	"SAP",
	"Susan Lough",
	"Sara Moon",
	"Savanna Group LTD - Savanna Samson",
	"ScanTool.net, LLC",
	"Schlyer Designs",
	"Scottcrew Enterprises",
	"Searching for Louis Media",
	"Secret-of-Art",
	"Seeing with Sound - The vOICe",
	"Sensation Press",
	"Sensual Candle",
	"Sew Terific Designs",
	"Sewing Bee Crinoline Ladies Embroidery Patterns",
	"Shabby Chic",
	"Sheridan Douglas Press",
	"Shimano, Inc",
	"SEISCO International Limited",
	"Shewee Ltd",
	"Shiseido Company Limited",
	"Shop Vac Corporation",
	"Sigma Beauty",
	"Sigmacumlaude.com",
	"Simon Carey",
	"Simpler Trading, LLC",
	"Sinister Mfg. Co., Inc. (Sinister Diesel)",
	"Skiboards Superstore, Inc.",
	"Sky Deutschland Fernsehen GmbH & Co. KG",
	"SmarterFresh, LLC",
	"SmartSound Software, Inc.",
	"SMS Audio, LLC",
	"SnakeEmporium.com",
	"Snap-on Incorporated",
	"SnugglyCat Inc - The Ripple Rug",
	"Society for Human Resource Management",
	"SockDock, LLC",
	"SoClean, Inc.",
	"Software & Information Industry Association (SIIA)",
	"Sole Technology, Inc.",
	"SoloWork Studio",
	"Sony Ericsson Mobile Communications AB",
	"Southwest Pictures / Southwest Entertainment Group, LLC",
	"SpiceFit",
	"Spicer Pro, LLC",
	"Sprint Corporation",
	"Spyder Active Sports, Inc.",
	"Standard Innovation Corporation",
	"Star Alliance Services GmbH",
	"Stephen Shore, photographs",
	"Stromberg Carburetor Ltd.",
	"STS Industries Inc. - NageBee",
	"Stussy Inc.",
	"STV Motorsports LLC",
	"Sue Coffee",
	"Sugru (FormFormForm Ltd)",
	"SummitFashions",
	"Suncast Corporation",
	"Sunrider International",
	"Surgical Appliance Industries, Inc.",
	"SuZhou Aobani Trading Company Ltd.",
	"Swarovski North America Limited",
	"Swift Response, LLC",
	"Swiss Army Brands, Inc.",
	"Sylver Designs",
	"Symantec",
	"Synergetics",
	"Tactical Beard Owners Club (TBOC)",
	"Tad-Bits Baby Items and More LLC",
	"Takata Corporation",
	"Tamiya America, Inc.",
	"Tania R. Chase",
	"TASER International Inc.",
	"Team Mysterio, Inc.",
	"Technica USA (Moon Boot)",
	"Technical Video, LLC",
	"TechSmith Corporation",
	"Tecscan of North Florida, Inc.",
	"Tekay Designs Inc.",
	"That's Greenius, LLC",
	"The Jewelry Channel Inc. dba Shop LC",
	"The Juice Plus, Company",
	"The LifeVantage Corporation",
	"These Please Ltd",
	"Third Man Records",
	"Thomas Losh",
	"ThreadABead",
	"Three Dogs and a Cat Inc.",
	"TidyEmu",
	"Tiffany & Company",
	"Tiger Tom Pistone Race Cars & Parts",
	"TigerDirect",
	"Time Tracker Technology",
	"TMH Technology Co., Ltd.",
	"To Your Home Ltd",
	"Tokentools Pty Ltd",
	"TokyoFlash Japan",
	"Tom Kelley Studios, Inc.",
	"Tomei Powered USA Inc.",
	"Tommy Hilfiger",
	"Top Secret Recipes",
	"Tori Richard, Ltd.",
	"Total Family Ministries",
	"Total Gym",
	"Tottenham Hotspur Ltd",
	"ToughCOINS LLC",
	"TrailerSauce",
	"Trainingmask, LLC",
	"Treasured Hungarian Family Recipes TM",
	"Tshirt Bordello",
	"Turbosmart",
	"TÃœV Markenverbund e.V",
	"TÃ¼v SÃ¼d",
	"Twinkl Ltd",
	"UGG Holdings, Inc.",
	"UGS Corp.",
	"Ultimate Creations, Inc. / Ultimate Warrior / Warrior",
	"Ultimate Sports Franchise Agents",
	"Ultimate Pet Nutrition, LLC",
	"Ultra Glow Cosmetics LTD",
	"Ultramax Products Limited",
	"Umbro International Limited",
	"Underwriters Laboratories, Inc.",
	"Uni-Trend Technology Co., Ltd",
	"United States Forest Service - USDA",
	"University of Iowa",
	"Ursula Hock-Henschke",
	"Vacheron Constantin",
	"Vale Science Technology Co. Ltd",
	"Van Cleef & Arpels",
	"Vanguard Industries, Inc.",
	"Velcro Companies",
	"Vera Bradley",
	"Versace",
	"Vickie Milazzo Institute",
	"Victory Seed Co.",
	"Vietnam International Video",
	"Vintage Cigarette Lighters",
	"Vintage Fans, L.L.C.",
	"Viper Interactive",
	"Virgil C. Stephens",
	"Vivint, Inc.",
	"VKR Holding A/S (VELUX)",
	"Volkswagen Corporation",
	"Vortex Optics",
	"Walker Metalsmiths Celtic Jewelry",
	"Walnut Studiolo LLC",
	"Ware Family Genealogy",
	"Warner Music Group",
	"Warner's Blue Ribbon Books on Swarovski",
	"Water Pik, Inc",
	"Wax Liquidizer Ltd.",
	"WD Music Products, Inc.",
	"Weinstein Company, The",
	"West American Corporation d/b/a RBH Sound",
	"West Frames, Inc.",
	"WH Software Limited",
	"Whelen Engineering Company, Inc.",
	"Whizardries, Inc.",
	"Whole Body Research, LLC",
	"Wiggles Touring Pty Limited, The",
	"Windmill-Parts.com",
	"With You Designs, LLC and With You Lockets",
	"Wonder Wizards",
	"World Hockey Association, LLC",
	"World Wrestling Entertainment, Inc. (WWE)",
	"Worldwide Women Artists (WWAO)",
	"WristWidget",
	"WÃ¼rth Srl",
	"X Bats",
	"XBMC Solutions Ltd - Droidbox",
	"Xiangzhiheng Electronics Inc.",
	"X-mini Capsule Speakers",
	"XPressMart.com",
	"Y&T - Meniketti",
	"Yogitoes",
	"Younique, LLC",
	"Your Baby Can, LLC.",
	"Yubo Technology Co.Ltd.",
	"Yum! Brands, Inc.",
	"Yvonne Hedley",
	"Z Produx Inc.",
	"ZAGG",
	"Zamboni",
	"Zappos.com",
	"Zen Design Group Ltd",
	"Zephyr Vaporizers", //More Vero from online"3 Sprouts",
	"4Life",
	"Adobe",
	"AEM",
	"Ammo",
	"Ammunition",
	"AmScope",
	"Angelynn",
	"AntennaX",
	"ArcSoft",
	"Arm's Reach",
	"Baby K'tan",
	"Beach Body",
	"Belkin",
	"Benchmade",
	"Big Boss",
	"Blowgun",
	"Boba",
	"Bose",
	"Broadway Basketeers",
	"Bumbleride",
	"Cabeau",
	"Car Scenter Electric Diffuser",
	"Cards Against Humanity",
	"Centerforce",
	"Chazpro",
	"Choon's Design",
	"Cisco-Linksys",
	"Classic Ultrasonic Aromatherapy Diffuser",
	"Columbia",
	"Cozy Sack",
	"Crabs Adjust Humidity",
	"Crystal Allies Gallery",
	"Daimler",
	"Daimler AG",
	"De'Longhi",
	"Deere",
	"DeLaine's",
	"DeLonghi",
	"DeWalt",
	"Diesel Zero",
	"Dr. Natura",
	"Dre Beats",
	"Dreamline",
	"DrNatura",
	"EcoSphere",
	"EDGE PRODUCTS",
	"Ergo baby",
	"Ergobaby",
	"Firearm",
	"Flare",
	"Flowmaster",
	"Forever 21",
	"Frux",
	"Furminator",
	"Furminator",
	"Gerber",
	"Goal Zero",
	"Goja",
	"Gratiae",
	"Grenadine Apparel",
	"Grizzly",
	"Grover",
	"GU Original",
	"Hewlett-Packard",
	"Hoover",
	"HP",
	"Hubmar",
	"Husky Liners",
	"Hypertech",
	"i2x",
	"Ideal Industries",
	"Image Vital C",
	"Induction Innovations",
	"InStyler",
	"IQAir",
	"iRobot",
	"Jewelry Organizer",
	"K&N",
	"Kicker",
	"Kimberly-Carr",
	"Kleinn",
	"Law Enforcement",
	"LEDGLOW",
	"LifeVantage",
	"Linksys",
	"Lionsgate",
	"LunchBots",
	"MacNeil",
	"Magic Bullet",
	"Magmatic",
	"Manfrotto",
	"Mavala",
	"McDavid",
	"Melaleuca",
	"Mishimoto",
	"Moen",
	"Mophie",
	"Moshi",
	"My Pillow",
	"MyPillow",
	"Nautilus",
	"Neewer",
	"Nemoba",
	"Neocutis",
	"Nest",
	"Ninja Master",
	"Nordic Naturals",
	"NOW Foods",
	"NutriBullet",
	"Otter Box",
	"OXO",
	"Paradise Galleries",
	"Philips Norelco",
	"RAZER",
	"Real Flame",
	"Reditainer",
	"Rigid",
	"RioRand",
	"Schwabel",
	"Seat Belt Extender",
	"Sennheiser",
	"Sephra",
	"Seven Towns",
	"Shure",
	"Sigma",
	"Simple human",
	"Simplehuman",
	"simplicam",
	"slimbelly",
	"Snap-On",
	"SnapOn",
	"Sony",
	"Speck",
	"Spin Master",
	"Star Kids",
	"STX INTERNATIONAL",
	"Superchips",
	"Tangle Teezer",
	"Thermacell",
	"Thule",
	"Tommie Copper",
	"Trebco",
	"True Religion",
	"Trunki",
	"TRX",
	"Tuft & Needle",
	"Ultra Herbal",
	"United Pet",
	"Vampire Squid Cards",
	"VersaLiving",
	"Vtooland",
	"VWAQ",
	"Waterpik",
	"WeatherTech",
	"Weber",
	"Westin",
	"William Mark",
	"Wow Cup",
	"Wow Gear",
	"WubbaNub",
	"Wyndmere",
	"Yankee Candle",
	"Zhao Xiang",
	"Zip gun",
	"Zumba",
	"What Do You Meme",
	"WowWee Group Ltd",
	"E. I. du Pont de Nemours and Company (DuPont)",
	"Ontel Products Corporation",
	"Fjerry, LLC dba What Do You Meme, LLC",
	"Procter & Gamble Company",
	"BeachBody, LLC",
	"Zumba",
	"Zumba", //New List 12/6/2019 From Hockey-Grandpa"Dorco",
	"Apple",
	"Roku", //New list 12/18/2019 from both"Hamilton Beach",
	"Ninja",
	"Remington",
	"Kwikset",
	"Weiser",
	"Baldwin",
	"National Hardware",
	"Pfister",
	"George Foreman",
	"Russell Hobbs",
	"Black,Decker",
	"Tetra",
	"Marineland",
	"GloFish",
	"Nature’s Miracle",
	"Dingo",
	"8-in-1",
	"FURminator",
	"IAMS",
	"Eukanuba",
	"Dorco",
	"Apple",
	"BeachBody",
	"Pampers",
	"Tide",
	"Downy",
	"Bounce",
	"Ivory Snow",
	"Gain",
	"Bounty",
	"Charmin",
	"Always",
	"Tampax",
	"Always Discreet",
	"Pantene",
	"Head & Shoulders",
	"Herbal Essences",
	"Old Spice",
	"Hair Food",
	"Swiffer",
	"Dawn",
	"Febreze",
	"Mr. Clean",
	"Cascade",
	"Gillette",
	"Braun",
	"Gilette Venus",
	"Vicks",
	"Metamucil",
	"Align",
	"Zzzquil",
	"Pepto-Bismol",
	"Clearblue",
	"Crest",
	"Oral-B",
	"Scope",
	"Secret",
	"Olay",
	"What Do You Meme",
	"5 Second Fix",
	"Arctic Air Ultra",
	"Bowl Light",
	"Breathe Easy",
	"Dryer Balls",
	"Dust Daddy",
	"Ever Brite Ultra",
	"Furniture Feet",
	"Gopher",
	"Handy Brite",
	"Handy Heater",
	"Huggle Hoodie",
	"Huggle Pets",
	"Huggle Socks",
	"Hurri Clean",
	"Iron Gym",
	"Magic Pad",
	"Magic Tracks",
	"Micro Mechanic",
	"Might Sight",
	"Mighty Sight",
	"Miracle Bamboo Bra",
	"Miracle Bamboo Cushion",
	"Miracle Bamboo Pillow",
	"Miracle Of Aloe",
	"Miracle Socks",
	"Piggy Pop",
	"Pillow Pad",
	"Pink Armor",
	"Posture Doctor",
	"Relief Wrap Ultra",
	"Simply Straight",
	"Speed Out",
	"Strutz",
	"Swivel Sweeper",
	"Tiger Wrench",
	"Turbo Jet",
	"Turbo Pump",
	"Turbo Scrub",
	"Turbo Snake",
	"Veggetti",
	"Veggetti Power",
	"Veggetti Pro",
	"Kevlar",
	"Nomex",
	"Corian",
	"Tyvek",
	"Sorona",
	"Danisco",
	"GREAT STUFF",
	"Styrofoam",
	"WowWee",
	"Shark",
	"Ninja",
	"Roku",

	//Vero veroTitleKeyWordsList =

	"Dorco",
	"Apple",
	"3Skulls Paintball",
	"AAT - The Association of Acounting Technicians",
	"Abercrombie & Fitch",
	"Action Mining Services Inc.",
	"Adobe",
	"ADT",
	"Air Force One Air Conditioning",
	"Aircraft Technical Publishers",
	"Alaska Airlines",
	"Aleratec, Inc.",
	"Alex Perez",
	"Alfresco Heating",
	"ALIENTECH SRL",
	"All Saints (Retail) Ltd",
	"ALM Productions",
	"Aloe of America, Inc. & Forever Living Products Int'l.",
	"Amari Bliss",
	"AMC Photographics Limited",
	"Americana International Ltd.",
	"American Eagle Outfitters",
	"American Weigh Scales, Inc.",
	"American Welding Society",
	"Americas Drive-In Corp. / Sonic Corp. & Subsidiaries",
	"Amiclubwear.com",
	"Amway Corporation (US)",
	"Amybug's Attic",
	"AnalogMan Guitar Effects",
	"Andrew James Worldwide",
	"Andy Thomas",
	"Angela LaFramboise",
	"Annenberg Media",
	"Ansonia Records, Inc.",
	"Anvil Forge Art",
	"Apex Tool Group",
	"AQUALIBRA UK",
	"AR15.com",
	"Arduino, LLC",
	"ARIIX, LLC",
	"Artbeats Software, Inc.",
	"Arturia",
	"Ashleigh Talbot",
	"AsKoruBeads",
	"Atlantic Research and Marketing (A.R.M.S.)",
	"Atvimports",
	"Auntie Anne's, Inc.",
	"Austin City Limits/KLRU",
	"Australian Gold, Inc.",
	"Australian Made Campaign Limited",
	"Authentic Brands Group LLC",
	"Autism Speaks, Inc.",
	"Autodata Limited",
	"Auto Meter Products, Inc. (Autometer)",
	"Autoline Industries",
	"Automotive Technologies, Inc.",
	"Avedis Zildjian, Co.",
	"B&M Racing",
	"B. C. Broncos",
	"B.H.P., Inc. dba Nialaya Jewelry",
	"Bad Monkey Productions",
	"Bally Pinball Fun",
	"Barnett Research and Computer Imaging",
	"Barstool Sports, Inc.",
	"Baume & Mercier",
	"Beachbody, LLC",
	"Bed Band Store",
	"Bell Helicopter Textron Inc.",
	"Benchmade Knife Company, Inc.",
	"Beyond Cell",
	"Beverly Hills MD",
	"Bill Lawrence Products",
	"Bill Owen-Cowboy Artist",
	"Billie W. Taylor II, Ph.D.",
	"BINO Products, LLC",
	"Biotrade Bulgaria Ltd.",
	"BioTrust Nutrition",
	"BISSELL Homecare, Inc.",
	"Bittrex, Inc.",
	"Blackpoint Engineering, LLC",
	"Blitzburgh Sports",
	"Blockware, LLC dba Great Useful Stuff",
	"Bloomberg L.P.",
	"BlossomSugarArt",
	"Bluetooth",
	"Bombardier Recreational Products, Inc.",
	"Bonnie's Plants",
	"Boppy Company, The",
	"Bose Corporation",
	"Botanissa LLC - See U Baby",
	"Boveda, Inc.",
	"Brenda Franklin",
	"Brian Smith",
	"Bridgestone Brands, LLC",
	"Brisant Secure Ltd",
	"British Phonographic Industry Limited",
	"Bronze Gallery",
	"Browning Laboratories, Inc.",
	"Bruce Lee Enterprises",
	"Bua, Inc.",
	"Buck Knives, Inc.",
	"Bug Me Video Inc.",
	"Bumbleride Inc.",
	"Burberry Limited",
	"Burlen Fuel System Limited",
	"Bushnell Performance Optics and Tasco Sales Pty Ltd.",
	"Business Software Alliance (EU)",
	"Bwthynbach",
	"Calutech, Inc.",
	"Canadian Standards Association",
	"Canon, Inc.",
	"Canyon Chenille, Inc.",
	"Canyon Dancer Motorcycle Products",
	"Care Creations, Inc.",
	"Car-Freshner Corporation",
	"Carl McCoy (Fields of the Nephilim)",
	"Carlstar Group â€“ ITP and Carlisle Brands",
	"Carmen's Vintage Collections",
	"Carmix-GPS",
	"Carrs Coins and Rocks, Inc.",
	"Cartier",
	"CBS Entertainment and Desilu, too, LLC (Unforgettable Licensing)",
	"CBT Nuggets, Inc",
	"CeraNet, Inc.",
	"Chalk & Vermilion Fine Arts",
	"Chanel, Inc.",
	"Charles Cook",
	"Chaz Dean Studio",
	"Chemsavers, Inc.",
	"Chevron Corporation",
	"Chief Architect, Inc.",
	"ChloÃ©",
	"Chocolate Starfish Ltd.",
	"Chubby Chico Charms LLC",
	"classic-video",
	"Clayful Creations",
	"Cloanto IT srl",
	"CLOCHE COUTURE TRADEMARK",
	"Cloud B, Inc.",
	"Coach, Inc.",
	"Cocktailier LLC",
	"ColArt Americas, Inc.",
	"Coldwater Creek Inc.",
	"Collar and Cuffs London",
	"Colnago America, Inc.",
	"ColorMetrics LLC/ HairMarker LLC",
	"ComitÃ© Georges Mathieu",
	"ComitÃ© Champagne",
	"Competition Clutch",
	"Continental Airlines",
	"Continental Enterprises",
	"Cool Mobility - Johanson Nominees Pty.",
	"Coquetry Clubwear",
	"Cosanti Originals by Paolo Soleri",
	"Country Collectibles",
	"Coway Co., Ltd",
	"Cozy Glow Ltd.",
	"Craft-e-Creations",
	"Cranberry Card Company",
	"Crazy Aaron's Puttyworld (Crazy Aaron's Thinking Putty)",
	"Creative Carvings by Monte",
	"Creature Comforts Ltd dba Cornwall Stoneware Co.",
	"Creeks End Crochet",
	"Criswell Embroidery & Design",
	"Crocs, Inc.",
	"Cucusoft, Inc.",
	"Cutco Cutlery Corporation",
	"Cutecolors.com",
	"Cynthia Dakin",
	"Cypress Collectibles",
	"Dais Enterprises",
	"Danes-R-Us Great Dane & Pet Art",
	"Daniel Bingham Design Studio",
	"Dansko, LLC",
	"Danworkshop.com",
	"Dark Horse Comics, Inc.",
	"DarkHorse Ranch, Inc.",
	"Dash America dba Pearl Izumi, Inc.",
	"Dassault Systemes S.A.",
	"data-professionals",
	"Dave Fant Company Of Arkansas Inc",
	"Dave's Discount Motors",
	"David Barton",
	"Davidson Photography",
	"DB Research L.L.P.",
	"Dedo Weigert Film GmbH",
	"Dell Computer Corp.",
	"Delphi Technologies",
	"Delta Air Lines, Inc.",
	"DermalMedix",
	"Dermalogica, Inc.",
	"DFLK Inc.",
	"Dick Harrell Performance Center, Inc. ('DHPC Inc.') Licensing Department",
	"Diesel (London) Ltd.",
	"Digium, Inc.",
	"Dinnages (1989)",
	"Dionne Quintuplets, The",
	"DMS International",
	"Doctor's Associates Inc. dba Subway",
	"Doggie Bow Ties",
	'Dolby Laboratories Inc. ("Dolby")',
	"Dollar Shave Club",
	"Dongguan Hawson Jewelry",
	"DONMAR Enterprises, Inc. - SKYROOFÂ®",
	"Don't Die, LLC",
	"Doria International, Inc.",
	"DPCD",
	"Dr. Denese - SkinScience Labs, Inc.",
	"Drageekiss Ltd.",
	"DressThatMan.com",
	"Drive-In Exchange, Ltd",
	"DropCrate, LLC",
	"DSMB Partners, LLC DBA ActivatedYou",
	"DTX International",
	"Duke of Pearl, LLC",
	"Dunhill",
	"Dunlop Manufacturing, Inc.",
	"Duracell U.S. Operations, Inc.",
	"Dynamic Resource Group",
	"E.I. du Pont de Nemours and Company",
	"Eagle Creek Enterprises - Tim Cox Fine Art",
	"Eames Office - Lucia Eames",
	"Eason Media Ltd",
	"East Direct (UK) Ltd",
	"Easton Sports Inc.",
	"Eclipse Records, Inc.",
	"Ecosphere Associates, Inc.",
	"Edgar Rice Burroughs, Inc.",
	"Edison Nation",
	"EFI Live Limited Co.",
	"Electro-Harmonix Effects",
	"Elope Inc.",
	"Ember Candles",
	"ENERGYbits Inc.",
	"Environ Skin Care Pty Ltd",
	"Epic Coolers",
	"Epson (UK) Corporation",
	"Ergo Baby Carrier, Inc.",
	"Erica Skadsen/Organic",
	"ESA - Entertainment Software Association",
	"Etienne Aigner AG",
	"etrailer.com",
	"Eurotech Photographics",
	"Exel Products",
	"EzyDog LLC",
	"Fab1Direct Ltd - Fablogix",
	"FabJob.com",
	"Fabriika",
	"Facelift Ent. Inc.",
	"Farmland Foods, Inc.",
	"Fashion Polish",
	"Fast Eddie's Vape Shop and Lounge, LLC",
	"FCA US, LLC",
	"FC Bayern MÃ¼nchen",
	"Federal Express Corporation (FedEx)",
	"Federation Against Copyright Theft (FACT) Ltd",
	"FÃ©dÃ©ration Internationale de Football Association (FIFA)",
	"Fender Musical Instruments Corporation",
	"Ferret Company",
	"FGM Ventures, LLC dba Petpost",
	"FileMaker, Inc.",
	"Fire Cam",
	"Fire House Neon LLC",
	"First Group / First Great Western",
	"Fishman",
	"Fitness Brands Inc. / Direct Entertainment Media Group",
	"FJA Mods",
	"Fleurville Florida Council of Bromeliad Societies, Inc.",
	"Flexibrace",
	"Flowmaster",
	"Fluidity Enterprises, Inc.",
	"Footprints Publishings Inc.",
	"Ford Motor Company",
	"FORMUFIT LLC",
	"Fort Worth Stock Show & Rodeo",
	"Foscam Intelligent Technology Co., Ltd.",
	"Foshan Shunde Shines E-Commerce Co., Ltd",
	"Fossil Reproductions",
	"Fossil, Inc.",
	"Fox (Twentieth Century Fox Film Corporation)",
	"Fretless Finger Guides",
	"Frantic Stamper, Inc.",
	"Frito-Lay, Inc.",
	"Fujikura Composites",
	"Funding USA LLC",
	"G. Loomis, Inc.",
	"Gaiam, Inc.",
	"Galiva Inc.",
	"Games 4 Hens Ltd",
	"Garden Selections Ltd.",
	"Garmin (UK)",
	"Garry Winogrand Photography",
	"Gaylord Entertainment Company",
	"General Motors",
	"Geneva Laboratories Ltd",
	"Georgia Pacific Corp.",
	"Georgie Girl Australia",
	"Gerber Childrenswear, LLC",
	"Getonfleek",
	"Giant UK LTD",
	"Gibson Brands, Inc.",
	"Gibson Performance Exhaust",
	"Giraffe Bath & Body, LLC",
	"Glenns Auto Repair and Performance LLC dba Glenns Auto Performance",
	"GMV Productions",
	"GN Netcom, dba Jabra",
	"Go Nutrients",
	"Gorilla Tech LTD",
	"Gottlieb Development, LLC",
	"GQ Electronics",
	"Grand Chapter of Phi Sigma Kappa, Inc.",
	"Grand Lodge Fraternal Order of Police",
	"Grandma Moses Properties Company",
	"Graphics Technology HK Limited",
	"Graphite Design, Inc.",
	"Graydog Woodenware",
	"Gretsch Company",
	"GrimmSpeed",
	"GUESS and MARCIANO Brands",
	"Gundry MD",
	"GUNNAR Optiks, LLC",
	"Guthy-Renker Corporation",
	"H&M",
	"Hair Flair LTD",
	"Harley-Davidson Motor Company",
	"Hartley Loudspeakers,Inc.",
	"HDMI Licensing, LLC",
	"Heirs and Estate of Peter William Ham",
	"Hells Angels Motorcycle Corporation Italia",
	"Herschel Supply Company Ltd.",
	"Hewlett-Packard Company (HP Ink & Toner)",
	"HIDS4UÂ®",
	"High Island Health, LLC dba Aneros",
	"Hillstock Collection",
	"Himalaya Drug Company",
	"HK Wuppertal-Solingen-Remscheid",
	"HKS Europe Ltd",
	"Hoberman Designs",
	"Home Power, Inc.",
	"Hook-Eze Pty Ltd",
	"Horizon Hobby, Inc.",
	"HotBuckles",
	"HouseLabels.com",
	"Huggalugs North America",
	"Hugs Not Drugs",
	"Human Touch, LLC",
	"Hy Cite Corporation",
	"Hybrid Systems Ltd., Inc. (HSL)",
	"Hydor Group",
	"IE WORKS, LLC",
	"iFixit",
	"Illume Holding Company LLC",
	"Incipio Technologies, Inc.",
	"Infinite Prosperity USA, LLC - Bluesky Travel Group Pty Ltd",
	"Inline Tube, Inc.",
	"Innovative JK Products LLC",
	"Innovative Salon Products, Inc. (LOMA)",
	"Innovative Textiles Inc.",
	"Insert Knowledge Here",
	"Intenze",
	"International Commercial Television - ICTV Brands",
	"Intuit, Inc.",
	"inVitamin, LLC",
	"IQ Implant Devices",
	"iRobot Corporation",
	"It Works Marketing Compliance",
	"jackets4bikes",
	"Jaclin Dunne",
	"Jaguar & Land Rover",
	"James Andrew Grant",
	"Jayco (UK) Limited",
	"JEDirect Corp dba JETech Design",
	"Jemella Ltd",
	"Jenni Leigh Creations",
	"Jet Performance Products, Inc",
	"Jeweltailor Ltd.",
	"Jim Pace Magic",
	"JMDL Toys",
	"JNimports Ltd. dba Periea",
	"Jo Condrill",
	"John Deere",
	"Jordan Design",
	"Joseph Rorie",
	"Joy Kroeger Beckner, Classical Realism, from Hounds to Humans",
	"JRM Licensing",
	"JS&M Sales & Marketing Inc.",
	"JTY Imports/Exports Pty Ltd",
	"Juul, Inc.",
	"JuveTress",
	"K&M International, Inc. - Wild Republic",
	"K.W. Muth Company, Inc.",
	"Kai Z Feng Limited",
	"Kando Pictures Limited",
	"Kason Industries",
	"Kate Spade & Company",
	"KBA Enterprises LLC - Alban",
	"KE Health LLC, DBA BoriCap",
	"Kendama USA",
	"Kenu, Inc.",
	"KENVELO",
	"KeraFiber Europe Limited",
	"Kettle Foods Ltd",
	"Ketosource Ltd.",
	"Kikka Digga",
	"King Baby Studio",
	"King Technology, Inc.",
	"KiniArt Studios",
	"Klasvsa (Huixian Dakang Electronic Commerce Co., Ltd.)",
	"Kleinn Automotive Accessories",
	"Knowledge In Motion, Inc.",
	"Kronemann Design Studio Pty. Ltd. - House of Kronemann USA",
	"Kun Shoulder Rest",
	"Kyser",
	"La Boutique de Bacchus",
	"La Chemise Lacoste SA",
	"Langley Productions, Inc.",
	"Larry Hartsell Seminars, Inc.",
	"Las Vegas Wranglers Professional Hockey Team",
	"Laser Design Int'l, LLC",
	"LCR Health",
	"Lenny and Eva, Inc.",
	"LetterRip Decals",
	"Leupold & Stevens, Inc.",
	"Levi Strauss & Co.",
	"Lexmark International Inc.",
	"Lia Sophia Jewelery",
	"LifeProof - Treefrog",
	"Lifetrons Switzerland GmbH",
	"Lifted Research Group Inc. (L-R-G)",
	"Light & Dark Productions",
	"Linda McSweeney",
	"LinkedIn Corporation",
	"Lip InkÂ® International",
	"Lipsy Ltd",
	"Live Cell Research",
	"Lomo Industries Ltd.",
	"Longchamp",
	"Lori G Ashley",
	"Luxe Jewels, LLC dba Stella & Dot",
	"Luxe Purses",
	"Mad Dogg Athletics, Inc.",
	"Magnet Shop",
	"Magnetic Poetry",
	"Magnolia Rubberstamps",
	"Makaton Charity",
	"Mamiya America Corporation",
	"Manchester United",
	"Mannatech Incorporated",
	"Marianne's Sol Mate Socks, Inc.",
	"Mars, Inc.",
	"Mary Capan",
	"Master of Illusions Entertainment",
	"Matt Groening",
	"Mavala International",
	"McCain Photography",
	"McGregor Fashion Group NV",
	"mDesign",
	"Medcosouth Healthcare, LLC",
	"Medieval Moccasins",
	"Mellotron Archives",
	"Melville Direct, LLC dba Bits and Pieces",
	"Mercantile Station 2",
	"Merle Norman Cosmetics, Inc.",
	"Metropolitan Kitchen",
	"MGA Entertainment, Inc. - A.B.C. International",
	"Microsoft",
	"Mike Barrett Productions Ltd.",
	"Mikimoto America",
	"Minelab Electronics",
	"Miniclip SA",
	"Ministero delle politiche agricole â€” ICQRF",
	"Ministry of Defense",
	"Miraflex S.A.",
	"Mitchell Repair Information Company",
	"Mocka Products Pty Ltd",
	"Mooneyes USA, Inc.",
	"Motion Picture Association of America (MPAA)",
	"Moviecraft Inc.",
	"Mud Puppy Mold Company",
	"Multipure Int'l",
	"Mutbak",
	"My Pageant Kid",
	"My Poupette Enterprises Inc.",
	"MyGift Enterprise LLC",
	"MyStudyGroup101",
	"Mywalit",
	"N.V.E., Inc.",
	"Nandita Arts",
	"National Academy of Television Arts & Sciences",
	"National Board of Medical Examiners - NBMEÂ®",
	"National Historic Mining Initiative LC3",
	"National Products Inc. DBA Ram Mounts",
	"National Shooting Sports Foundation",
	"Naturally Plus",
	"NCH Software",
	"NetPicks, LLC",
	"New Era Cap Company",
	"Nichols Photography",
	"Nickolas Muray Photo Archives, LLC",
	"Nike",
	"Nintendo of America Inc.",
	"Nissin Foods Holdings",
	"Niwot Corporation dba Specialty Products Company",
	"Noico",
	"Nomination S.R.L.",
	"Nordstrom, Inc.",
	"NSK Americas, Inc.",
	"Nu Skin International Inc.",
	"Nucific",
	"Nutramax Laboratories, Inc.",
	"Oakley, Inc.",
	"Oki Data Corporation",
	"Ã–ko-Tex",
	"Old & Urban",
	"One Wise Mac Limited",
	"OnlineFabricStore",
	"Open University",
	"OPI Products, Inc",
	"Orange USA",
	"Organo Gold",
	"Orielle, LLC",
	"Origami Owl, LLC",
	"Orthotebb Health Shoes, LLC",
	"Osmosis Skincare",
	"Osnat",
	"Otterbox",
	"Overstock.com Inc.",
	"P Rogers, Inc.",
	"Pacific Market International, LLC",
	"Packard Club",
	"Paddington and Company Limited",
	"Pagedown Technology, LLC",
	"Pamp SA",
	"Pampered Chef, The",
	"Panasonic Corporation of North America",
	"Paradise Film Institute/Big Pictures",
	"Pasoday Products Ltd",
	"Patch Me Thru",
	"Patchexpertsus",
	"Patmont Motor Werks/Go-PedÂ®",
	"Pawsitively Perfect Bows",
	"PeachpopsClipArtâ„¢",
	"Peak Coffee Ltd",
	"Pen Press Publishing",
	"Peri K Designs",
	"Pevonia International, LLC",
	"Philosophy, Inc.",
	"Phiten GmbH",
	"Photomedex",
	"PiperWai, LLC",
	"Plans Designs",
	"Platinum Place",
	"Platypus Wear, Inc. dba Bad Boy Brands",
	"Playboy Enterprises",
	"Playtex Products, LLC",
	"Plexaderm",
	"Plexus Worldwide, Inc",
	"Ploom - Pax Labs",
	"Plumeria Bay, Inc.",
	"Pneumatic Components Ltd",
	"Polymorphe, Inc",
	"Pool Cover Corp. dba Loop Loc",
	"Poppy Company",
	"PopSockets LLC",
	"Portage Word-Wide, Inc. - Manhattan Portage",
	"Power Art Design Airbrushs Pty Ltd",
	"Power Straight",
	"PowerPortLA, LLC",
	"Practically Darling Designs",
	"Prada S.A.",
	"Pratico Goods, LLC",
	"Premier League",
	"PremiumFishing Auctions Store",
	"Princeton Nutrients",
	"Proactiv Company SÃ¡rl",
	"Probiotic America",
	"Procter & Gamble",
	"ProfessorProfits.com",
	"ProFroster",
	"Pronto Moda Global Limited",
	"Provo Craft & Novelty, Inc.",
	"Purdey",
	"Quane Cosmetics",
	"Quiksilver, Inc",
	"Rachel Caine",
	"Radiancy, Inc.",
	"Radio Flyer, Inc.",
	"Rainbow Sandals, Inc.",
	"Randomwalk, LLC",
	"Ranger Doug's Enterprises",
	"Rare Sportsfilms Inc.",
	"Rasasi Perfumes",
	"Ray-Ban",
	"Rayverstar LLC",
	"Razormaid! Productions",
	"RE/MAX International, Inc.",
	"Rea.Deeming Beauty, Inc. dba Beautyblender",
	"Red Bull GmbH",
	"Red Digital Cinema Camera Company",
	"Red Camel Racing Ltd.",
	"Red Hat Society, Inc.",
	"Red Monkey Designs, Inc.",
	"Red Steagall's Cowboy Corner",
	"Relix International, Inc.",
	"Relleciga Official",
	"Rembrandt Charms",
	"ReminderBand Inc.",
	"Remote Pro Pty Ltd",
	"Reshoevn8r",
	"Revelation Records",
	"Revitalash Cosmetics",
	"RGK Innovations LLC",
	"Rhodes International",
	"Richard Avedon Foundation",
	"Rideworx Pty Ltd.",
	"Ridgerock Tools",
	"Right Deals UK Limited",
	"Rivington Designs Ltd",
	"RN Study Spot",
	"Rocket Science Institute, Inc.",
	"Rodan",
	"Fields",
	"Rohde Fine Art",
	"Rolls-Royce",
	"Rosetta Stone (UK) Ltd",
	"Roth Company",
	"Rothstein Guitars",
	"Rowena Cherry",
	"Royal British Legion, The",
	"Royal Silk LTD",
	"RRO Entertainment",
	"Rude Awakening Coffee House",
	"Sacem",
	"Sado Nation",
	"Sadowsky Guitars Ltd.",
	"Sakura Color Products of America, Inc.",
	"Saleen",
	"Salt Gems LLC",
	"Salt Life Holdings, LLC",
	"SaltWorks, Inc.",
	"Santas Christmas Town",
	"Sanyo Electric Co., Ltd.",
	"SAP",
	"Susan Lough",
	"Sara Moon",
	"Savanna Group LTD - Savanna Samson",
	"ScanTool.net, LLC",
	"Schlyer Designs",
	"Scottcrew Enterprises",
	"Searching for Louis Media",
	"Secret-of-Art",
	"Seeing with Sound - The vOICe",
	"Sensation Press",
	"Sensual Candle",
	"Sew Terific Designs",
	"Sewing Bee Crinoline Ladies Embroidery Patterns",
	"Shabby Chic",
	"Sheridan Douglas Press",
	"Shimano, Inc",
	"SEISCO International Limited",
	"Shewee Ltd",
	"Shiseido Company Limited",
	"Shop Vac Corporation",
	"Sigma Beauty",
	"Sigmacumlaude.com",
	"Simon Carey",
	"Simpler Trading, LLC",
	"Sinister Mfg. Co., Inc. (Sinister Diesel)",
	"Skiboards Superstore, Inc.",
	"Sky Deutschland Fernsehen GmbH & Co. KG",
	"SmarterFresh, LLC",
	"SmartSound Software, Inc.",
	"SMS Audio, LLC",
	"SnakeEmporium.com",
	"Snap-on Incorporated",
	"SnugglyCat Inc - The Ripple Rug",
	"Society for Human Resource Management",
	"SockDock, LLC",
	"SoClean, Inc.",
	"Software & Information Industry Association (SIIA)",
	"Sole Technology, Inc.",
	"SoloWork Studio",
	"Sony Ericsson Mobile Communications AB",
	"Southwest Pictures / Southwest Entertainment Group, LLC",
	"SpiceFit",
	"Spicer Pro, LLC",
	"Sprint Corporation",
	"Spyder Active Sports, Inc.",
	"Standard Innovation Corporation",
	"Star Alliance Services GmbH",
	"Stephen Shore, photographs",
	"Stromberg Carburetor Ltd.",
	"STS Industries Inc. - NageBee",
	"Stussy Inc.",
	"STV Motorsports LLC",
	"Sue Coffee",
	"Sugru (FormFormForm Ltd)",
	"SummitFashions",
	"Suncast Corporation",
	"Sunrider International",
	"Surgical Appliance Industries, Inc.",
	"SuZhou Aobani Trading Company Ltd.",
	"Swarovski North America Limited",
	"Swift Response, LLC",
	"Swiss Army Brands, Inc.",
	"Sylver Designs",
	"Symantec",
	"Synergetics",
	"Tactical Beard Owners Club (TBOC)",
	"Tad-Bits Baby Items and More LLC",
	"Takata Corporation",
	"Tamiya America, Inc.",
	"Tania R. Chase",
	"TASER International Inc.",
	"Team Mysterio, Inc.",
	"Technica USA (Moon Boot)",
	"Technical Video, LLC",
	"TechSmith Corporation",
	"Tecscan of North Florida, Inc.",
	"Tekay Designs Inc.",
	"That's Greenius, LLC",
	"The Jewelry Channel Inc. dba Shop LC",
	"The Juice Plus, Company",
	"The LifeVantage Corporation",
	"These Please Ltd",
	"Third Man Records",
	"Thomas Losh",
	"ThreadABead",
	"Three Dogs and a Cat Inc.",
	"TidyEmu",
	"Tiffany & Company",
	"Tiger Tom Pistone Race Cars & Parts",
	"TigerDirect",
	"Time Tracker Technology",
	"TMH Technology Co., Ltd.",
	"To Your Home Ltd",
	"Tokentools Pty Ltd",
	"TokyoFlash Japan",
	"Tom Kelley Studios, Inc.",
	"Tomei Powered USA Inc.",
	"Tommy Hilfiger",
	"Top Secret Recipes",
	"Tori Richard, Ltd.",
	"Total Family Ministries",
	"Total Gym",
	"Tottenham Hotspur Ltd",
	"ToughCOINS LLC",
	"TrailerSauce",
	"Trainingmask, LLC",
	"Treasured Hungarian Family Recipes TM",
	"Tshirt Bordello",
	"Turbosmart",
	"TÃœV Markenverbund e.V",
	"TÃ¼v SÃ¼d",
	"Twinkl Ltd",
	"UGG Holdings, Inc.",
	"UGS Corp.",
	"Ultimate Creations, Inc. / Ultimate Warrior / Warrior",
	"Ultimate Sports Franchise Agents",
	"Ultimate Pet Nutrition, LLC",
	"Ultra Glow Cosmetics LTD",
	"Ultramax Products Limited",
	"Umbro International Limited",
	"Underwriters Laboratories, Inc.",
	"Uni-Trend Technology Co., Ltd",
	"United States Forest Service - USDA",
	"University of Iowa",
	"Ursula Hock-Henschke",
	"Vacheron Constantin",
	"Vale Science Technology Co. Ltd",
	"Van Cleef & Arpels",
	"Vanguard Industries, Inc.",
	"Velcro Companies",
	"Vera Bradley",
	"Versace",
	"Vickie Milazzo Institute",
	"Victory Seed Co.",
	"Vietnam International Video",
	"Vintage Cigarette Lighters",
	"Vintage Fans, L.L.C.",
	"Viper Interactive",
	"Virgil C. Stephens",
	"Vivint, Inc.",
	"VKR Holding A/S (VELUX)",
	"Volkswagen Corporation",
	"Vortex Optics",
	"Walker Metalsmiths Celtic Jewelry",
	"Walnut Studiolo LLC",
	"Ware Family Genealogy",
	"Warner Music Group",
	"Warner's Blue Ribbon Books on Swarovski",
	"Water Pik, Inc",
	"Wax Liquidizer Ltd.",
	"WD Music Products, Inc.",
	"Weinstein Company, The",
	"West American Corporation d/b/a RBH Sound",
	"West Frames, Inc.",
	"WH Software Limited",
	"Whelen Engineering Company, Inc.",
	"Whizardries, Inc.",
	"Whole Body Research, LLC",
	"Wiggles Touring Pty Limited, The",
	"Windmill-Parts.com",
	"With You Designs, LLC and With You Lockets",
	"Wonder Wizards",
	"World Hockey Association, LLC",
	"World Wrestling Entertainment, Inc. (WWE)",
	"Worldwide Women Artists (WWAO)",
	"WristWidget",
	"WÃ¼rth Srl",
	"X Bats",
	"XBMC Solutions Ltd - Droidbox",
	"Xiangzhiheng Electronics Inc.",
	"X-mini Capsule Speakers",
	"XPressMart.com",
	"Y&T - Meniketti",
	"Yogitoes",
	"Younique, LLC",
	"Your Baby Can, LLC.",
	"Yubo Technology Co.Ltd.",
	"Yum! Brands, Inc.",
	"Yvonne Hedley",
	"Z Produx Inc.",
	"ZAGG",
	"Zamboni",
	"Zappos.com",
	"Zen Design Group Ltd",
	"Zephyr Vaporizers", //More Vero from online"3 Sprouts",
	"4Life",
	"Adobe",
	"AEM",
	"Ammo",
	"Ammunition",
	"AmScope",
	"Angelynn",
	"AntennaX",
	"ArcSoft",
	"Arm's Reach",
	"Baby K'tan",
	"Beach Body",
	"Belkin",
	"Benchmade",
	"Big Boss",
	"Blowgun",
	"Boba",
	"Bose",
	"Broadway Basketeers",
	"Bumbleride",
	"Cabeau",
	"Car Scenter Electric Diffuser",
	"Cards Against Humanity",
	"Centerforce",
	"Chazpro",
	"Choon's Design",
	"Cisco-Linksys",
	"Classic Ultrasonic Aromatherapy Diffuser",
	"Columbia",
	"Cozy Sack",
	"Crabs Adjust Humidity",
	"Crystal Allies Gallery",
	"Daimler",
	"Daimler AG",
	"De'Longhi",
	"Deere",
	"DeLaine's",
	"DeLonghi",
	"DeWalt",
	"Diesel Zero",
	"Dr. Natura",
	"Dre Beats",
	"Dreamline",
	"DrNatura",
	"EcoSphere",
	"EDGE PRODUCTS",
	"Ergo baby",
	"Ergobaby",
	"Firearm",
	"Flare",
	"Flowmaster",
	"Forever 21",
	"Frux",
	"Furminator",
	"Furminator",
	"Gerber",
	"Goal Zero",
	"Goja",
	"Gratiae",
	"Grenadine Apparel",
	"Grizzly",
	"Grover",
	"GU Original",
	"Hewlett-Packard",
	"Hoover",
	"HP",
	"Hubmar",
	"Husky Liners",
	"Hypertech",
	"i2x",
	"Ideal Industries",
	"Image Vital C",
	"Induction Innovations",
	"InStyler",
	"IQAir",
	"iRobot",
	"Jewelry Organizer",
	"K&N",
	"Kicker",
	"Kimberly-Carr",
	"Kleinn",
	"Law Enforcement",
	"LEDGLOW",
	"LifeVantage",
	"Linksys",
	"Lionsgate",
	"LunchBots",
	"MacNeil",
	"Magic Bullet",
	"Magmatic",
	"Manfrotto",
	"Mavala",
	"McDavid",
	"Melaleuca",
	"Mishimoto",
	"Moen",
	"Mophie",
	"Moshi",
	"My Pillow",
	"MyPillow",
	"Nautilus",
	"Neewer",
	"Nemoba",
	"Neocutis",
	"Nest",
	"Ninja Master",
	"Nordic Naturals",
	"NOW Foods",
	"NutriBullet",
	"Otter Box",
	"OXO",
	"Paradise Galleries",
	"Philips Norelco",
	"RAZER",
	"Real Flame",
	"Reditainer",
	"Rigid",
	"RioRand",
	"Schwabel",
	"Seat Belt Extender",
	"Sennheiser",
	"Sephra",
	"Seven Towns",
	"Shure",
	"Sigma",
	"Simple human",
	"Simplehuman",
	"simplicam",
	"slimbelly",
	"Snap-On",
	"SnapOn",
	"Sony",
	"Speck",
	"Spin Master",
	"Star Kids",
	"STX INTERNATIONAL",
	"Superchips",
	"Tangle Teezer",
	"Thermacell",
	"Thule",
	"Tommie Copper",
	"Trebco",
	"True Religion",
	"Trunki",
	"TRX",
	"Tuft & Needle",
	"Ultra Herbal",
	"United Pet",
	"Vampire Squid Cards",
	"VersaLiving",
	"Vtooland",
	"VWAQ",
	"Waterpik",
	"WeatherTech",
	"Weber",
	"Westin",
	"William Mark",
	"Wow Cup",
	"Wow Gear",
	"WubbaNub",
	"Wyndmere",
	"Yankee Candle",
	"Zhao Xiang",
	"Zip gun",
	"Zumba",
	"What Do You Meme",
	"WowWee Group Ltd",
	"E. I. du Pont de Nemours and Company (DuPont)",
	"Ontel Products Corporation",
	"Fjerry, LLC dba What Do You Meme, LLC",
	"Procter & Gamble Company",
	"BeachBody, LLC",
	"Zumba",
	"Zumba", //New List 12/6/2019 From Hockey-Grandpa"Dorco",
	"Apple",
	"Roku", //New List 12/18/2019"Hamilton Beach",
	"Ninja",
	"Remington",
	"Kwikset",
	"Weiser",
	"Baldwin",
	"National Hardware",
	"Pfister",
	"George Foreman",
	"Russell Hobbs",
	"Black,Decker",
	"Tetra",
	"Marineland",
	"GloFish",
	"Nature’s Miracle",
	"Dingo",
	"8-in-1",
	"FURminator",
	"IAMS",
	"Eukanuba",
	"Dorco",
	"Apple",
	"BeachBody",
	"Pampers",
	"Tide",
	"Downy",
	"Bounce",
	"Ivory Snow",
	"Gain",
	"Bounty",
	"Charmin",
	"Always",
	"Tampax",
	"Always Discreet",
	"Pantene",
	"Head & Shoulders",
	"Herbal Essences",
	"Old Spice",
	"Hair Food",
	"Swiffer",
	"Dawn",
	"Febreze",
	"Mr. Clean",
	"Cascade",
	"Gillette",
	"Braun",
	"Gilette Venus",
	"Vicks",
	"Metamucil",
	"Align",
	"Zzzquil",
	"Pepto-Bismol",
	"Clearblue",
	"Crest",
	"Oral-B",
	"Scope",
	"Secret",
	"Olay",
	"What Do You Meme",
	"5 Second Fix",
	"Arctic Air Ultra",
	"Bowl Light",
	"Breathe Easy",
	"Dryer Balls",
	"Dust Daddy",
	"Ever Brite Ultra",
	"Furniture Feet",
	"Gopher",
	"Handy Brite",
	"Handy Heater",
	"Huggle Hoodie",
	"Huggle Pets",
	"Huggle Socks",
	"Hurri Clean",
	"Iron Gym",
	"Magic Pad",
	"Magic Tracks",
	"Micro Mechanic",
	"Might Sight",
	"Mighty Sight",
	"Miracle Bamboo Bra",
	"Miracle Bamboo Cushion",
	"Miracle Bamboo Pillow",
	"Miracle Of Aloe",
	"Miracle Socks",
	"Piggy Pop",
	"Pillow Pad",
	"Pink Armor",
	"Posture Doctor",
	"Relief Wrap Ultra",
	"Simply Straight",
	"Speed Out",
	"Strutz",
	"Swivel Sweeper",
	"Tiger Wrench",
	"Turbo Jet",
	"Turbo Pump",
	"Turbo Scrub",
	"Turbo Snake",
	"Veggetti",
	"Veggetti Power",
	"Veggetti Pro",
	"Kevlar",
	"Nomex",
	"Corian",
	"Tyvek",
	"Sorona",
	"Danisco",
	"GREAT STUFF",
	"Styrofoam",
	"WowWee",
	"Shark",
	"Ninja",
	"Roku",
];
